/**
 * The custom MDX pipeline (docs-site.md §1).
 *
 * MDX is compiled to plain TSX at docs build, ahead of the bundler: no MDX loader, no
 * docs framework, no runtime compilation. The bundler only ever sees ordinary React
 * modules, which keeps the pipeline independent of Next's loader plumbing.
 */

import { compile } from "@mdx-js/mdx";
import remarkGfm from "remark-gfm";

import type { ContentHeading } from "../../src/lib/docs-model.ts";
import { slugifyHeading } from "../../src/lib/slug.ts";

const HEADING = /^(#{2,4})\s+(.+?)\s*#*\s*$/;
const FENCE = /^\s*(?:```|~~~)/;

/** Headings the MDX body contributes to the on-page TOC. */
export function readContentHeadings(body: string): readonly ContentHeading[] {
  const headings: ContentHeading[] = [];
  let inFence = false;
  for (const line of body.split("\n")) {
    if (FENCE.test(line)) {
      inFence = !inFence;
      continue;
    }
    if (inFence) {
      continue;
    }
    const match = HEADING.exec(line);
    const hashes = match?.[1];
    const title = match?.[2];
    if (hashes === undefined || title === undefined) {
      continue;
    }
    headings.push({ id: slugifyHeading(title), title, depth: hashes.length });
  }
  return headings;
}

/**
 * Rewrites ATX headings to explicit JSX carrying the anchor id.
 *
 * Anchors are a build-time fact so the rendered heading and the on-page TOC cannot
 * disagree, and no rehype plugin or runtime heading component has to re-derive them.
 */
export function stampHeadingAnchors(body: string): string {
  let inFence = false;
  return body
    .split("\n")
    .map((line) => {
      if (FENCE.test(line)) {
        inFence = !inFence;
        return line;
      }
      if (inFence) {
        return line;
      }
      const match = HEADING.exec(line);
      const hashes = match?.[1];
      const title = match?.[2];
      if (hashes === undefined || title === undefined) {
        return line;
      }
      const tag = `h${String(hashes.length)}`;
      return `<${tag} id="${slugifyHeading(title)}">${title}</${tag}>`;
    })
    .join("\n");
}

/** True when the MDX body has anything to render beyond whitespace. */
export function hasBodyContent(body: string): boolean {
  return body.trim() !== "";
}

const GENERATED_BANNER = [
  "// @ts-nocheck",
  "/* Generated by apps/docs/scripts/generate.ts from an authored .mdx shell. Do not edit. */",
  "",
].join("\n");

/** Compiles one MDX body into a standalone TSX module. */
export async function compileMdx(body: string, filePath: string): Promise<string> {
  const compiled = await compile(
    { value: stampHeadingAnchors(body), path: filePath },
    {
      jsx: true,
      outputFormat: "program",
      development: false,
      remarkPlugins: [remarkGfm],
    }
  );
  return `${GENERATED_BANNER}${String(compiled)}`;
}
