export {
  ProjectExtractor,
  type ExtractionResult,
  type ProjectExtractorService,
  type SyntaxOnlyExtractionResult,
} from "./extractor.ts";
export { BackendError, ConfigError, ExtractError, FileNotInProgramError } from "./errors.ts";
export {
  ExtractionResultSchema,
  ModuleNodeSchema,
  SemanticTypeSchema,
  type CallSignatureNode,
  type ArrayNode,
  type ClassMethod,
  type ClassNode,
  type ClassProperty,
  type ComponentNode,
  type ConstructSignatureNode,
  type Documentation,
  type DocumentationTag,
  type EnumMember,
  type EnumNode,
  type ExportNode,
  type ExternalTypeNode,
  type FunctionNode,
  type IntrinsicName,
  type IntrinsicNode,
  type IntersectionNode,
  type IndexSignatureNode,
  type LiteralNode,
  type ModuleNode,
  type ParameterNode,
  type PropertyNode,
  type SemanticType,
  type SyntaxOnlyOutput,
  type SyntaxOnlyModuleNode,
  type ResolvedOutput,
  type ResolvedModuleNode,
  type TupleNode,
  type TypeArgument,
  type TypeOperatorNode,
  type TypeOperatorResolutionKind,
  type TypeParameterNode,
  type TypeQueryNode,
  type TypeName,
  type UnionNode,
} from "./model.ts";
export {
  defaultExtractorOptions,
  type ExtractorOptions,
  type OpenProjectOptions,
  type ProjectFileSystem,
  type ProjectFileSystemEntries,
  type ShouldIncludeData,
  type ShouldResolveObjectData,
  type TypeOperatorOutput,
  type TypeOperatorOutputMode,
} from "./options.ts";
export { ProvenanceEntrySchema, ProvenanceSchema, type ProvenanceEntry } from "./provenance.ts";
export {
  ExtractWarningSchema,
  MissingDefaultExportSymbolWarningSchema,
  MissingEnumDeclarationWarningSchema,
  UnsupportedTypeFallbackWarningSchema,
  type TypeFlagName,
  type ExtractWarning,
  type MissingDefaultExportSymbolWarning,
  type MissingEnumDeclarationWarning,
  type UnsupportedTypeFallbackWarning,
} from "./warnings.ts";
