/**
 * Every part declares a density role: which density metrics it reads. A part is a `data-slot` the
 * package writes. Where one slot renders with two roles, an override key, the slot followed by a
 * CSS selector suffix starting with `[` or `:`, such as `card[data-direction=horizontal]` or
 * `sidebar-group:where([data-collapsible=icon] *)` for the collapsed icon rail, overrides the role
 * for the instances `[data-slot="slot"]` plus that suffix matches. The first matching override in
 * table order wins.
 * CONTEXT.md defines the roles. The docs density coverage test renders every demo at both densities
 * and checks each instance: a `control`, `row`, `surface` or `label` part reads a metric of its
 * role through its height, padding, gap or type, even one that is the same at both densities, such
 * as `--surface-pad-sm`; a `layout` or `fixed` part reads none. The source contract requires every
 * written `data-slot` to be a key and every key to follow that grammar.
 */

/** The density roles, in the order CONTEXT.md defines them. */
export const DENSITY_ROLES = ["control", "row", "surface", "label", "layout", "fixed"] as const;

/** The metrics a part reads, or `layout` and `fixed` for a part that reads none. */
export type DensityRole = (typeof DENSITY_ROLES)[number];

/** Every part's density role, keyed by `data-slot` or by an override key. */
// oxlint-disable-next-line elmera/no-raw-class-map -- a role table, not classes: `fixed` is a role name
export const PART_DENSITY = {
  accordion: "layout",
  "accordion-item": "surface",
  "accordion-header": "layout",
  "accordion-trigger": "layout",
  "accordion-indicator": "fixed",
  "accordion-content": "layout",

  "alert-icon": "fixed",
  "alert-dialog-trigger": "control",

  avatar: "fixed",
  "avatar-image": "fixed",
  "avatar-fallback": "fixed",
  "avatar-group": "fixed",

  badge: "fixed",

  breadcrumb: "fixed",
  "breadcrumb-list": "fixed",
  "breadcrumb-item": "fixed",
  "breadcrumb-link": "fixed",
  "breadcrumb-page": "fixed",
  "breadcrumb-separator": "fixed",
  "breadcrumb-ellipsis": "fixed",

  button: "control",
  "button[data-size=icon-inline]": "fixed",
  "button-pending-indicator": "fixed",

  "button-group": "layout",
  "button-group-separator": "layout",
  "button-group-text": "layout",

  card: "layout",
  "card[data-direction=horizontal]": "surface",
  "card-header": "surface",
  "card-header[data-direction=horizontal]": "layout",
  "card-title": "fixed",
  "card-description": "fixed",
  "card-action": "layout",
  "card-content": "surface",
  "card-content[data-direction=horizontal]": "layout",
  "card-footer": "surface",
  "card-footer[data-direction=horizontal]": "layout",
  "card-tag": "fixed",

  checkbox: "fixed",
  "checkbox-indicator": "fixed",
  "checkbox-group": "surface",
  "checkbox-group[data-direction=vertical]:has(> [data-selection-item])": "layout",
  "checkbox-item": "surface",

  code: "fixed",

  collapsible: "fixed",
  "collapsible-trigger": "fixed",
  "collapsible-content": "fixed",

  "combobox-value": "layout",
  "combobox-trigger": "fixed",
  "combobox-clear": "control",
  "combobox-content": "layout",
  "combobox-list": "surface",
  "combobox-collection": "layout",
  "combobox-empty": "row",
  "combobox-group": "layout",
  "combobox-label": "row",
  "combobox-item": "row",
  "combobox-separator": "fixed",
  "combobox-chips": "control",
  "combobox-chip": "fixed",
  "combobox-chip-remove": "fixed",
  "combobox-chip-input": "layout",
  "input-group-button": "control",

  "data-table-header": "layout",
  "data-table-body": "layout",
  "data-table-row": "layout",
  "data-table-skeleton-row": "layout",
  "data-table-empty-row": "layout",
  "data-table-text": "fixed",
  "data-table-number": "fixed",
  "data-table-currency": "fixed",
  "data-table-date": "fixed",
  "data-table-date-time": "fixed",
  "data-table-sort-button": "control",
  "data-table-select-all": "fixed",
  "data-table-select-row": "fixed",
  "data-table-row-actions": "control",
  "data-table-actions-header": "fixed",
  "data-table-column-toggle": "control",
  "data-table-pagination": "layout",
  "data-table-page-status": "fixed",
  "data-table-page-controls": "layout",

  "description-list": "layout",
  "description-list-heading": "fixed",
  "description-list-content": "layout",
  "description-list-term": "row",
  "description-list-details": "row",

  dialog: "layout",
  "dialog-trigger": "control",
  "dialog-portal": "layout",
  "dialog-overlay": "fixed",
  "dialog-content": "surface",
  "dialog-header": "layout",
  "dialog-title": "fixed",
  "dialog-description": "fixed",
  "dialog-footer": "layout",
  "dialog-close": "control",

  "dropdown-menu": "layout",
  "dropdown-menu-trigger": "control",
  "dropdown-menu-portal": "layout",
  "dropdown-menu-content": "surface",
  "dropdown-menu-sub-content": "surface",
  "dropdown-menu-group": "layout",
  "dropdown-menu-label": "row",
  "dropdown-menu-item": "row",
  "dropdown-menu-link-item": "row",
  "dropdown-menu-checkbox-item": "row",
  "dropdown-menu-checkbox-item-indicator": "fixed",
  "dropdown-menu-radio-group": "layout",
  "dropdown-menu-radio-item": "row",
  "dropdown-menu-radio-item-indicator": "fixed",
  "dropdown-menu-separator": "fixed",
  "dropdown-menu-shortcut": "fixed",
  "dropdown-menu-sub": "layout",
  "dropdown-menu-sub-trigger": "row",

  emoji: "fixed",

  empty: "surface",
  "empty-header": "layout",
  "empty-media": "fixed",
  "empty-title": "fixed",
  "empty-description": "fixed",
  "empty-content": "layout",

  field: "surface",
  "field[data-spacing=part]": "layout",
  "field-set": "surface",
  "field-legend": "label",
  "field-legend[data-variant=legend]": "fixed",
  "field-group": "surface",
  "field-content": "layout",
  "field-label": "label",
  "field-title": "label",
  "field-control": "control",
  "field-description": "label",
  "field-item": "layout",
  "field-separator": "fixed",
  "field-separator-content": "fixed",
  "field-error": "label",
  "field-input": "control",

  form: "layout",

  frame: "surface",
  "frame-panel": "surface",
  "frame-panel-header": "surface",
  "frame-panel-title": "fixed",
  "frame-panel-description": "fixed",
  "frame-panel-footer": "surface",

  heading: "fixed",

  input: "control",

  "input-group": "control",
  "input-group:is(:has(> textarea), :has(> [data-align^=block]))": "layout",
  "input-group-addon": "control",
  "input-group-text": "control",
  "input-group-control": "control",

  item: "surface",
  "item-group": "surface",
  "item-group[data-variant=compact]": "layout",
  "item-group[data-direction=vertical]": "layout",
  "item-separator": "fixed",
  "item-listitem": "layout",
  "item-media": "fixed",
  "item-content": "layout",
  "item-title": "fixed",
  "item-description": "fixed",
  "item-actions": "layout",
  "item-header": "layout",
  "item-footer": "layout",
  "item-footer-content": "layout",

  loader: "fixed",

  meter: "fixed",
  "meter-label": "fixed",
  "meter-value": "fixed",
  "meter-bar": "fixed",
  "meter-bar-fill": "fixed",

  "navigation-menu": "layout",
  "navigation-menu-list": "layout",
  "navigation-menu-item": "layout",
  "navigation-menu-trigger": "control",
  "navigation-menu-content": "surface",
  "navigation-menu-link": "row",
  "navigation-menu-indicator": "fixed",
  "navigation-menu-viewport": "layout",
  "navigation-menu-popup": "layout",

  pagination: "layout",
  "pagination-content": "layout",
  "pagination-item": "layout",
  "pagination-link": "control",
  "pagination-previous": "control",
  "pagination-next": "control",
  "pagination-ellipsis": "control",

  popover: "layout",
  "popover-trigger": "control",
  "popover-content": "surface",
  "popover-header": "layout",
  "popover-title": "fixed",
  "popover-description": "fixed",

  "radio-group": "surface",
  "radio-group[data-direction=vertical]:has(> [data-selection-item])": "layout",
  "radio-group-item": "fixed",
  "radio-group-indicator": "fixed",
  "radio-icon-button": "control",
  "radio-item": "surface",

  "scroll-area": "fixed",
  "scroll-area-viewport": "fixed",
  "scroll-area-content": "fixed",
  "scroll-area-scrollbar": "fixed",
  "scroll-area-thumb": "fixed",

  "select-trigger": "control",
  "select-value": "layout",
  "select-content": "layout",
  "select-group": "surface",
  "select-label": "row",
  "select-item": "row",
  "select-separator": "fixed",
  "select-scroll-up-button": "fixed",
  "select-scroll-down-button": "fixed",

  "selection-item-control": "surface",
  "selection-item-title": "label",
  "selection-item-description": "label",
  "selection-item-sub-sections": "layout",

  separator: "fixed",

  sheet: "layout",
  "sheet-trigger": "control",
  "sheet-portal": "layout",
  "sheet-overlay": "fixed",
  "sheet-viewport": "layout",
  "sheet-content": "layout",
  "sheet-content-inner": "surface",
  "sheet-header": "surface",
  "sheet-title": "fixed",
  "sheet-description": "fixed",
  "sheet-body": "surface",
  "sheet-footer": "surface",
  "sheet-close": "control",

  sidebar: "layout",
  "sidebar-wrapper": "layout",
  "sidebar-gap": "layout",
  "sidebar-container": "layout",
  "sidebar-inner": "layout",
  "sidebar-trigger": "control",
  "sidebar-icon": "fixed",
  "sidebar-rail": "fixed",
  "sidebar-inset": "layout",
  "sidebar-input": "row",
  "sidebar-header:where([data-collapsible=icon] *)": "fixed",
  "sidebar-header": "surface",
  "sidebar-footer:where([data-collapsible=icon] *)": "fixed",
  "sidebar-footer": "surface",
  "sidebar-separator": "fixed",
  "sidebar-content": "layout",
  "sidebar-group:where([data-collapsible=icon] *)": "fixed",
  "sidebar-group": "surface",
  "sidebar-group-label": "row",
  "sidebar-group-action": "control",
  "sidebar-group-content": "layout",
  "sidebar-menu": "layout",
  "sidebar-menu-item": "layout",
  "sidebar-menu-button:where([data-collapsible=icon] *)": "fixed",
  "sidebar-menu-button": "row",
  "sidebar-menu-button[data-size=sm]": "fixed",
  "sidebar-menu-button[data-size=lg]": "fixed",
  "sidebar-menu-action:is([data-slot=sidebar-menu-button][data-size=sm] ~ *)": "fixed",
  "sidebar-menu-action:is([data-slot=sidebar-menu-button][data-size=lg] ~ *)": "fixed",
  "sidebar-menu-action": "control",
  "sidebar-menu-badge": "fixed",
  "sidebar-menu-skeleton:where([data-collapsible=icon] *)": "fixed",
  "sidebar-menu-skeleton": "row",
  "sidebar-menu-skeleton-icon": "fixed",
  "sidebar-menu-skeleton-text": "fixed",
  "sidebar-menu-sub": "layout",
  "sidebar-menu-sub-item": "layout",
  "sidebar-menu-sub-button": "row",

  skeleton: "fixed",

  slider: "layout",
  "slider-control": "control",
  "slider-track": "fixed",
  "slider-indicator": "fixed",
  "slider-thumb": "fixed",
  "slider-value": "label",

  span: "fixed",

  switch: "fixed",
  "switch-thumb": "fixed",

  "table-container": "layout",
  table: "layout",
  "table-header": "layout",
  "table-body": "layout",
  "table-footer": "layout",
  "table-row": "layout",
  "table-head": "row",
  "table-cell": "row",
  "table-caption": "fixed",
  "vertical-table-root": "layout",
  "vertical-table": "layout",
  "vertical-table-body": "layout",
  "vertical-table-header": "fixed",

  tabs: "layout",
  "tabs-list": "control",
  "tabs-list[data-orientation=vertical]": "layout",
  "tabs-trigger": "control",
  "tabs-content": "layout",

  text: "fixed",

  textarea: "control",

  "timeline-list": "fixed",
  "timeline-list-item": "fixed",
  "timeline-list-dot": "fixed",
  "timeline-list-title": "fixed",
  "timeline-list-time": "fixed",
  "timeline-list-description": "fixed",

  "toast-viewport": "layout",
  "toast-root": "surface",
  "toast-content": "layout",
  "toast-title": "fixed",
  "toast-description": "fixed",
  "toast-action": "control",
  "toast-close": "control",

  toggle: "control",

  "toggle-group": "layout",
  "toggle-group-item": "control",

  "tooltip-provider": "layout",
  tooltip: "layout",
  "tooltip-trigger": "control",
  "tooltip-content": "surface",

  "date-picker-preset-group": "surface",
  "date-picker-preset-item": "row",
  "date-range-picker-preset-group": "surface",
  "date-range-picker-preset-item": "row",
  "grid-list": "layout",
  "grid-list-item": "row",
  // plop:density-part
} as const satisfies Readonly<Record<string, DensityRole>>;

/** A `PART_DENSITY` key: a `data-slot`, or the slot followed by a CSS selector suffix. */
export type DensityPart = keyof typeof PART_DENSITY;
