import createMdx from "@next/mdx";
import type { NextConfig } from "next";
import path from "node:path";
import { fileURLToPath } from "node:url";

const workspaceRoot = path.join(path.dirname(fileURLToPath(import.meta.url)), "../..");

const nextConfig: NextConfig = {
  outputFileTracingRoot: workspaceRoot,
  /** Component pages are authored as `page.mdx` route files. */
  pageExtensions: ["ts", "tsx", "mdx"],
  /**
   * `next dev` otherwise writes `AGENTS.md`/`CLAUDE.md` into this app on every start.
   * Agent instructions in this repo are authored, not generated by a dev server.
   */
  agentRules: false,
};

/**
 * Plugins are named as strings, not imported functions: Turbopack hands loader options
 * to Rust, so a function reference cannot cross that boundary. The same string list is
 * resolved by the webpack loader, so `next dev --turbopack` and `next build` compile MDX
 * through one configuration.
 *
 * - `remark-frontmatter` claims the `---` block, so it is metadata for the build to read
 *   (the lede — see `scripts/lib/page-source.ts`) rather than rendered prose.
 * - `remark-gfm` keeps tables, strikethrough and autolinks available to page authors.
 */
const withMdx = createMdx({
  options: {
    remarkPlugins: ["remark-frontmatter", "remark-gfm"],
  },
});

export default withMdx(nextConfig);
