import type { ResolvedColorScheme } from "./color-scheme-types";
import { composeTheme } from "./compose-theme";
import { brandPointer } from "./tokens/brand-pointers";
import type { BrandPointer } from "./tokens/brand-pointers";
import { derivedRoleSources, EXTERNAL_RESET_KEYS, isDerivedTokenName, TOKEN_NAMES } from "./tokens/contract";
import type { TokenContract, TokenName } from "./tokens/contract";
import { DEFAULTS } from "./tokens/defaults";
import { derivedRoleCss } from "./tokens/derived-tokens";
import { PRIMITIVE_NAMES, PRIMITIVES } from "./tokens/primitives";
import { THEME_RESET_KEYS } from "./tokens/reset-keys";
import { BRAND_CODES, BRANDS, LEGAL_THEMES } from "./tokens/themes";
import type { BrandCode, ThemeInput } from "./tokens/themes";

const GENERATED_FILE_HEADER = `/**
 * AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY.
 *
 * Generated by the token pipeline. TypeScript theme modules are the source of truth.
 */

`;

function cssCustomProperty(name: string, value: string): string {
  return `  --${name}: ${value};`;
}

/**
 * The value a theme rule declares for one composed role. A mixed derived role declares its
 * live `color-mix()`, so the browser mixes the sources of the element that carries the rule.
 * Every other role declares its composed value. The catalog, the docs and design tools
 * read the composed literals.
 */
function cssValue(name: TokenName, value: string): string {
  return isDerivedTokenName(name) ? derivedRoleCss(name, value) : value;
}

function cssRule(
  selectors: readonly string[],
  declarations: readonly (readonly [string, string])[],
  colorScheme?: ResolvedColorScheme
): string {
  const body = declarations.map(([name, value]) => cssCustomProperty(name, value));
  if (colorScheme !== undefined) body.push(`  color-scheme: ${colorScheme};`);
  return `${selectors.join(",\n")} {\n${body.join("\n")}\n}`;
}

/**
 * Light rules target one selector; dark rules carry the direct and the descendant
 * form in one selector list so a palette body is emitted once, not twice.
 */
function themeRule(
  selector: string,
  declarations: readonly (readonly [string, string])[],
  colorScheme: ResolvedColorScheme
): string {
  if (colorScheme === "dark") {
    return cssRule(
      [`[data-theme="dark"]${selector}`, `[data-theme="dark"] ${selector}`],
      declarations,
      "dark"
    );
  }
  return cssRule([selector], declarations, "light");
}

function rootDeclarations(): (readonly [string, string])[] {
  const primitives = PRIMITIVE_NAMES.map((name) => [name, PRIMITIVES[name]] as const);
  const roles = TOKEN_NAMES.map((name) => [name, cssValue(name, DEFAULTS[name])] as const);
  return [...primitives, ...roles];
}

/**
 * Light layers declare `EXTERNAL_RESET_KEYS` only, so a host override of a role no
 * palette owns (`--ring`, `--popover`, `--chart-*`) inherits through the scope. Dark
 * layers materialize `THEME_RESET_KEYS`, every key any light or dark palette can change.
 */
function resetDeclarations(
  overrides: Partial<TokenContract>,
  keys: readonly TokenName[]
): (readonly [string, string])[] {
  return keys.map((key) => [key, cssValue(key, overrides[key] ?? DEFAULTS[key])] as const);
}

function resetKeys(colorScheme: ResolvedColorScheme): readonly TokenName[] {
  return colorScheme === "dark" ? THEME_RESET_KEYS : EXTERNAL_RESET_KEYS;
}

function emitRoot(): string {
  return cssRule([":root"], rootDeclarations());
}

const POINTER_KEYS: ReadonlySet<TokenName> = new Set([
  "brand",
  "brand-foreground",
] satisfies (keyof BrandPointer)[]);

/**
 * The derived roles that read the brand pointer. A host restyles a brand at the pointer's
 * weight, one attribute such as `.app[data-theme-brand="tkas"]`, so no rule declares these
 * roles at more than that weight. The brand pointer carries their light values, and every
 * dark palette rule leaves them to a companion rule that puts its scheme and variant
 * qualifiers in `:where()`.
 */
const BRAND_SCOPED_KEYS = TOKEN_NAMES.filter(
  (name) => isDerivedTokenName(name) && derivedRoleSources(name).some((source) => POINTER_KEYS.has(source))
);

function brandScopedDeclarations(tokens: TokenContract): (readonly [string, string])[] {
  return BRAND_SCOPED_KEYS.map((key) => [key, cssValue(key, tokens[key])] as const);
}

/** A dark palette rule's declarations: its reset keys, less the brand-scoped roles. */
function darkPaletteDeclarations(tokens: TokenContract): (readonly [string, string])[] {
  return resetDeclarations(
    tokens,
    resetKeys("dark").filter((key) => !BRAND_SCOPED_KEYS.includes(key))
  );
}

/**
 * The companion of a dark palette rule: the brand-scoped roles for one brand, with the
 * scheme and the palette's other qualifiers weighing nothing. It ties the brand pointer and
 * follows it, so it wins over the pointer's light values, and a host override at the
 * pointer's weight that comes later wins over it.
 */
function darkBrandScopedRule(qualifiers: string, brand: BrandCode, tokens: TokenContract): string {
  const subject = `[data-theme-brand="${brand}"]`;
  return cssRule(
    [
      `:where([data-theme="dark"]${qualifiers})${subject}`,
      `:where([data-theme="dark"] ${qualifiers})${subject}`,
    ],
    brandScopedDeclarations(tokens)
  );
}

function internalTheme(brand: BrandCode): ThemeInput {
  const theme = LEGAL_THEMES.find(
    (candidate) => candidate.variant === "internal" && candidate.brand === brand
  );
  if (theme === undefined) {
    throw new Error(`Brand ${brand} has no legal internal theme`);
  }
  return theme;
}

function emitBrandPointers(): string {
  return BRAND_CODES.map((code) => {
    const pointer = brandPointer(code);
    return cssRule(
      [`[data-theme-brand="${code}"]`],
      [
        ["brand", pointer.brand],
        ["brand-foreground", pointer["brand-foreground"]],
        ...brandScopedDeclarations(composeTheme(internalTheme(code), "light")),
      ]
    );
  }).join("\n\n");
}

function emitInternalReset(): string {
  return themeRule(`[data-theme-variant="internal"]`, resetDeclarations({}, resetKeys("light")), "light");
}

/**
 * The internal variant has one palette for every brand, so one composed internal dark
 * theme names the dark scope's declarations. Its brand pointer is not part of
 * `THEME_RESET_KEYS`, so the choice of brand and segment does not matter.
 */
function internalDarkTheme(): ThemeInput {
  const theme = LEGAL_THEMES.find((candidate) => candidate.variant === "internal");
  if (theme === undefined) {
    throw new Error("No internal theme is legal");
  }
  return theme;
}

function emitInternalDarkPalette(): string {
  const variant = `[data-theme-variant="internal"]`;
  const palette = themeRule(
    variant,
    darkPaletteDeclarations(composeTheme(internalDarkTheme(), "dark")),
    "dark"
  );
  // The shared palette is brand-agnostic, but the brand-scoped roles follow the brand.
  const brandScoped = BRAND_CODES.map((code) =>
    darkBrandScopedRule(variant, code, composeTheme(internalTheme(code), "dark"))
  );
  return [palette, ...brandScoped].join("\n\n");
}

/**
 * The roles a segment changes against its brand base. A derived role counts as changed
 * wherever one of its sources does, because the rule must declare its `color-mix()` again
 * to mix the segment's sources instead of inheriting the base's result.
 */
function changedKeys(base: TokenContract, tokens: TokenContract): TokenName[] {
  const differs = (key: TokenName): boolean => tokens[key] !== base[key];
  return TOKEN_NAMES.filter((key) =>
    isDerivedTokenName(key) ? derivedRoleSources(key).some(differs) : differs(key)
  );
}

/** True when the two compositions differ in any token. */
function differsFrom(base: TokenContract, tokens: TokenContract): boolean {
  return changedKeys(base, tokens).length > 0;
}

/**
 * Emit each brand's rule from its composed base theme, then a segment rule wherever the
 * segment departs from that base. Light segment rules carry only the changed keys; dark
 * segment rules materialize the full reset set like every other dark rule.
 *
 * A segment that departs only in light still gets a dark rule: the light segment selector
 * (`[variant][brand][segment]`) ties the dark brand selector (`[dark][variant][brand]`),
 * so without the four-attribute dark segment rule a dark scope would resolve that tie by
 * emission order instead of by specificity.
 */
function emitBrandPalettes(colorScheme: ResolvedColorScheme): string {
  const rules: string[] = [];
  for (const brand of BRAND_CODES) {
    const themes = LEGAL_THEMES.filter((theme) => theme.variant === "external" && theme.brand === brand);
    // Resolve the base by the brand's first segment rather than `themes[0]`, so base
    // selection does not depend on `LEGAL_THEMES` ordering. Its rule carries no
    // `data-theme-segment`, so it is the fallback an element without a segment — or
    // with a segment that has no sheet — resolves.
    const [baseSegment] = BRANDS[brand].segments;
    const baseTheme = themes.find((theme) => theme.segment === baseSegment);
    if (baseTheme === undefined) {
      throw new Error(`Brand ${brand} has no legal external themes`);
    }
    const base = composeTheme(baseTheme, colorScheme);
    // The dark arm also asks whether the segment departs in light, so it needs the light
    // base beside the composed base it already holds.
    const lightBase = colorScheme === "dark" ? composeTheme(baseTheme, "light") : base;
    const variant = `[data-theme-variant="external"]`;
    const selector = `${variant}[data-theme-brand="${brand}"]`;
    if (colorScheme === "dark") {
      rules.push(themeRule(selector, darkPaletteDeclarations(base), "dark"));
      rules.push(darkBrandScopedRule(variant, brand, base));
    } else {
      rules.push(themeRule(selector, resetDeclarations(base, resetKeys("light")), "light"));
    }
    for (const theme of themes.filter((candidate) => candidate !== baseTheme)) {
      const lightTokens = composeTheme(theme, "light");
      const lightDeparts = differsFrom(lightBase, lightTokens);
      const tokens = colorScheme === "light" ? lightTokens : composeTheme(theme, "dark");
      // A light-only departure still gets its dark rule, so the four-attribute dark
      // segment selector wins the tie with the light segment selector by specificity.
      const departs = colorScheme === "light" ? lightDeparts : lightDeparts || differsFrom(base, tokens);
      // tkas, guen and elma have a company segment but no sheet, so they get no rule in
      // either scheme.
      if (!departs) continue;
      const segment = `[data-theme-segment="${theme.segment}"]`;
      if (colorScheme === "dark") {
        rules.push(themeRule(`${selector}${segment}`, darkPaletteDeclarations(tokens), "dark"));
        // It follows the base companion at the same weight, so the segment's values win.
        rules.push(darkBrandScopedRule(`${variant}${segment}`, brand, tokens));
      } else {
        const declarations = changedKeys(base, tokens).map(
          (key) => [key, cssValue(key, tokens[key])] as const
        );
        rules.push(themeRule(`${selector}${segment}`, declarations, "light"));
      }
    }
  }
  return rules.join("\n\n");
}

/**
 * Composing every theme is a guard, not a computation: `composeTheme` throws when a
 * theme is missing its must-override tokens, so generation fails loudly on the same
 * contract the theme tests assert.
 */
function assertAllThemesCompose(): void {
  for (const theme of LEGAL_THEMES) {
    composeTheme(theme);
    composeTheme(theme, "dark");
  }
}

export function generateThemesCss(): string {
  assertAllThemesCompose();

  return [
    GENERATED_FILE_HEADER.trimEnd(),
    emitRoot(),
    emitBrandPointers(),
    emitInternalReset(),
    emitBrandPalettes("light"),
    emitInternalDarkPalette(),
    emitBrandPalettes("dark"),
    "",
  ].join("\n\n");
}
