import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, realpathSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { evaluateColorSchemeBootstrapScript } from "./color-scheme-bootstrap-harness";
import { exportKey, toPosix } from "./entries";
import type { DiscoveredEntries } from "./entries";
import {
  assertFlagPayload,
  flagHashFailure,
  flagPayload,
  listFlagFiles,
  parseProvenanceHashes,
} from "./flag-assets";
import { buildPublishExportMap, exportBindingsObject } from "./generate-exports";
import type { ExportBinding, ExportCondition } from "./generate-exports";
import {
  emittedDirectiveFailure,
  packedBareEntryRacDeclarationFailure,
  packedValueExportFailure,
  parsePackedEvalJson,
} from "./package-check-lib";
import { twemojiNoticeFailure } from "./twemoji-notices";

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..");

export function fail(message: string): never {
  console.error(message);
  process.exit(1);
}

export function importSpecifier(subpath: string): string {
  return subpath === "." ? "@elmeragroup/ui" : `@elmeragroup/ui/${subpath}`;
}

export function importPackedModules(
  consumerRoot: string,
  specifiers: readonly string[]
): Record<string, string[]> {
  const result = spawnSync(
    process.execPath,
    [
      "--input-type=module",
      "--eval",
      `const specifiers = ${JSON.stringify(specifiers)};
const exported = {};
for (const specifier of specifiers) {
  const mod = await import(specifier);
  exported[specifier] = Object.keys(mod).sort();
}
process.stdout.write(JSON.stringify(exported));`,
    ],
    { cwd: consumerRoot, encoding: "utf8" }
  );
  if (result.status !== 0) {
    fail(`Node ESM import failed:\n${result.stderr || result.stdout}`);
  }
  const parsed = parsePackedEvalJson(result.stdout, "packed entries");
  if (!parsed.ok) {
    fail(parsed.failure);
  }
  if (parsed.value === null || Array.isArray(parsed.value) || Object(parsed.value) !== parsed.value) {
    fail(`Unexpected import payload: ${result.stdout}`);
  }
  // SAFETY: the eval prints JSON.stringify of specifier → sorted export name arrays.
  return parsed.value as Record<string, string[]>;
}

type PackedPeers = {
  react?: string;
  "react-dom"?: string;
  tailwindcss?: string;
};

type PackedManifest = {
  exports: ReturnType<typeof exportBindingsObject>;
  peerDependencies: PackedPeers;
  dependencies?: Record<string, string>;
};

type PackedManifestRead = {
  packed: PackedManifest;
  packedText: string;
};

function isExportCondition(target: ExportBinding["target"]): target is ExportCondition {
  return Object(target) === target;
}

function isExportTargetPath(target: ExportBinding["target"]): target is string {
  return Object.prototype.toString.call(target) === "[object String]";
}

function packedManifest(extracted: string): PackedManifestRead {
  const packedText = readFileSync(join(extracted, "package.json"), "utf8");
  const parsed: unknown = JSON.parse(packedText);
  if (parsed === null || Array.isArray(parsed)) {
    fail("Packed package.json is not an object");
  }
  // SAFETY: packed package.json is generated by writePublishManifest.
  return { packed: parsed as PackedManifest, packedText };
}

export function checkPackedExports(extracted: string, discovered: DiscoveredEntries): void {
  const expectedBindings = buildPublishExportMap(discovered);
  const { packed } = packedManifest(extracted);
  if (JSON.stringify(packed.exports) !== JSON.stringify(exportBindingsObject(expectedBindings))) {
    fail("Packed package.json exports do not match the generated publish map.");
  }

  for (const binding of expectedBindings) {
    const target = binding.target;
    if (isExportCondition(target)) {
      const jsPath = join(extracted, target.import.replace(/^\.\//, ""));
      const dtsPath = join(extracted, target.types.replace(/^\.\//, ""));
      if (!existsSync(jsPath)) {
        fail(`Packed import for ${binding.key} missing ${target.import}`);
      }
      if (!existsSync(dtsPath)) {
        fail(`Packed types for ${binding.key} missing ${target.types}`);
      }
      continue;
    }
    if (isExportTargetPath(target)) {
      if (target.includes("*")) {
        continue;
      }
      const filePath = join(extracted, target.replace(/^\.\//, ""));
      if (!existsSync(filePath)) {
        fail(`Packed CSS/asset export ${binding.key} missing file ${target}`);
      }
      continue;
    }
    fail(`Unexpected export target for ${binding.key}: ${JSON.stringify(target)}`);
  }
}

export function checkPackedPeers(extracted: string): void {
  const { packed, packedText } = packedManifest(extracted);
  const peers = packed.peerDependencies;
  if (peers.react !== "^19" || peers["react-dom"] !== "^19") {
    fail(`Packed react peer ranges must be ^19, got ${JSON.stringify(peers)}`);
  }
  if (peers.tailwindcss !== "^4") {
    fail(`Packed tailwindcss peer range must be ^4, got ${JSON.stringify(peers.tailwindcss)}`);
  }
  if (packedText.includes("catalog:")) {
    fail("Packed package.json leaked catalog: pins");
  }
  if (packed.dependencies?.["libphonenumber-js"] !== undefined) {
    fail("Packed package.json must not publish libphonenumber-js as a runtime dependency");
  }
}

export function checkPackedRuntimeExports(
  exported: Record<string, string[]>,
  discovered: DiscoveredEntries
): void {
  for (const entry of discovered.jsEntries) {
    const specifier = importSpecifier(entry.subpath);
    const names = exported[specifier];
    if (names === undefined) {
      fail(`Packed import missing ${specifier}`);
    }
    const mismatch = packedValueExportFailure(exportKey(entry.subpath), names, entry.runtimeExports);
    if (mismatch !== undefined) {
      fail(mismatch);
    }
  }
}

export function checkPackedFlags(
  extracted: string,
  consumerRoot: string,
  flagsNames: readonly string[] | undefined
): void {
  const flagsDir = join(extracted, "flags");
  if (!existsSync(flagsDir)) {
    fail("Packed flags/ directory is missing");
  }
  if (!existsSync(join(flagsDir, "LICENSE"))) {
    fail("Packed flags/ is missing LICENSE");
  }
  if (!existsSync(join(flagsDir, "PROVENANCE.md"))) {
    fail("Packed flags/ is missing PROVENANCE.md");
  }

  const svgs = listFlagFiles(flagsDir);
  try {
    assertFlagPayload(flagPayload(flagsDir, svgs));
  } catch (error) {
    fail(error instanceof Error ? error.message : String(error));
  }
  const hashFailure = flagHashFailure(
    flagsDir,
    svgs,
    parseProvenanceHashes(readFileSync(join(flagsDir, "PROVENANCE.md"), "utf8"))
  );
  if (hashFailure !== undefined) {
    fail(hashFailure);
  }
  for (const code of ["NO", "SE", "FI"]) {
    if (!existsSync(join(flagsDir, `${code}.svg`))) {
      fail(`Packed flags/ is missing ${code}.svg`);
    }
  }

  if (flagsNames === undefined || !flagsNames.includes("flagAssets")) {
    fail(`Packed /flags is missing flagAssets: ${(flagsNames ?? []).join(", ")}`);
  }
  const urlsResult = spawnSync(
    process.execPath,
    [
      "--input-type=module",
      "--eval",
      `import { flagAssets } from "@elmeragroup/ui/flags";
const urls = [flagAssets.NO, flagAssets.SE, flagAssets.FI];
process.stdout.write(JSON.stringify(urls));`,
    ],
    { cwd: consumerRoot, encoding: "utf8" }
  );
  if (urlsResult.status !== 0) {
    fail(`Packed flagAssets URLs failed:\n${urlsResult.stderr || urlsResult.stdout}`);
  }
  const parsedUrls = parsePackedEvalJson(urlsResult.stdout, "flagAssets URLs");
  if (!parsedUrls.ok) {
    fail(parsedUrls.failure);
  }
  if (!Array.isArray(parsedUrls.value)) {
    fail(`Unexpected flagAssets URL payload: ${urlsResult.stdout}`);
  }
  for (const url of parsedUrls.value) {
    // Packed JSON I/O boundary: the eval'd importer prints JSON.stringify of URL strings.
    // oxlint-disable-next-line anti-slop/no-runtime-typeof
    if (typeof url !== "string") {
      fail(`flagAssets URL is not a string: ${JSON.stringify(url)}`);
    }
    if (/^(https?:|data:|blob:)/.test(url)) {
      fail(`flagAssets URL used a forbidden scheme: ${url}`);
    }
    const resolved = url.startsWith("file:") ? fileURLToPath(url) : join(extracted, url.replace(/^\.\//, ""));
    if (!existsSync(resolved)) {
      fail(`flagAssets URL does not resolve to a packed file: ${url}`);
    }
    const flagsRoot = `${toPosix(realpathSync(join(extracted, "flags")))}/`;
    if (!toPosix(realpathSync(resolved)).startsWith(flagsRoot)) {
      fail(`flagAssets URL resolved outside packed flags/: ${url}`);
    }
  }
}

function packedColorSchemeScriptSource(consumerRoot: string, optionsLiteral: string): string {
  const result = spawnSync(
    process.execPath,
    [
      "--input-type=module",
      "--eval",
      `import { colorSchemeScriptSource } from "@elmeragroup/ui/theme";
process.stdout.write(colorSchemeScriptSource(${optionsLiteral}));`,
    ],
    { cwd: consumerRoot, encoding: "utf8" }
  );
  if (result.status !== 0) {
    fail(`Packed colorSchemeScriptSource failed:\n${result.stderr || result.stdout}`);
  }
  return result.stdout;
}

export function checkPackedBootstrap(consumerRoot: string, themeNames: readonly string[] | undefined): void {
  if (
    themeNames === undefined ||
    !themeNames.includes("colorSchemeScriptSource") ||
    !themeNames.includes("ColorSchemeScript")
  ) {
    fail(`Packed /theme is missing bootstrap exports: ${(themeNames ?? []).join(", ")}`);
  }

  const scriptBreak = "</script>";
  const lineSeparator = "\u2028";
  const paragraphSeparator = "\u2029";
  const primitives = {
    storageKey: `${scriptBreak}"&${lineSeparator}${paragraphSeparator}`,
    defaultColorScheme: "system",
    enableSystem: true,
    forcedColorScheme: "dark",
  };
  const source = packedColorSchemeScriptSource(consumerRoot, JSON.stringify(primitives));
  if (source.includes(scriptBreak)) {
    fail("Packed bootstrap serialized a raw </script> sequence");
  }
  if (!source.includes("\\u003c/script>")) {
    fail("Packed bootstrap did not escape </script> as \\u003c/script>");
  }
  if (!source.includes("\\u2028") || !source.includes("\\u2029")) {
    fail("Packed bootstrap did not escape U+2028 / U+2029");
  }
  if (source.includes("&quot;") || source.includes("&amp;") || source.includes("&lt;")) {
    fail("Packed bootstrap HTML-entity-encoded script data");
  }
  if (!source.includes("&") || !source.includes('\\"')) {
    fail("Packed bootstrap lost raw quotes or ampersands");
  }

  const result = evaluateColorSchemeBootstrapScript(source, { storedValue: "light", prefersDark: false });
  if (result.attributes["data-theme"] !== "dark") {
    fail(`Packed forced bootstrap wrote data-theme=${String(result.attributes["data-theme"])}`);
  }
  if (result.storageReads.length > 0) {
    fail("Packed forced bootstrap read storage");
  }
  if (JSON.stringify(result.manifest) !== JSON.stringify(primitives)) {
    fail(`Packed bootstrap manifest mismatch: ${JSON.stringify(result.manifest)}`);
  }
  if (result.style.colorScheme !== undefined || result.createdElements.length > 0) {
    fail("Packed bootstrap wrote CSS color-scheme or created elements");
  }

  const systemSource = packedColorSchemeScriptSource(consumerRoot, `{ enableSystem: false }`);
  const systemResult = evaluateColorSchemeBootstrapScript(systemSource, {
    storedValue: "system",
    prefersDark: true,
  });
  if (systemResult.attributes["data-theme"] !== "light") {
    fail("Packed bootstrap did not resolve disabled system to light");
  }
}

export function checkPackedTwemojiNotices(extracted: string): void {
  const failure = twemojiNoticeFailure(extracted);
  if (failure !== undefined) {
    fail(`Packed Twemoji notices: ${failure}`);
  }
}

export function checkPackedDirectives(extracted: string, discovered: DiscoveredEntries): void {
  const mismatch = emittedDirectiveFailure(extracted, discovered.sourceFiles, packageRoot);
  if (mismatch !== undefined) {
    fail(mismatch);
  }
}

export function checkPackedBareEntryRacDeclarations(extracted: string, discovered: DiscoveredEntries): void {
  const leak = packedBareEntryRacDeclarationFailure(extracted, discovered.jsEntries);
  if (leak !== undefined) {
    fail(leak);
  }
}

export function checkValidateThemeEnv(extracted: string): void {
  const packed = join(extracted, "theme/validate-theme.js");
  if (!existsSync(packed)) {
    fail("Packed graph is missing theme/validate-theme.js");
  }
  if (!readFileSync(packed, "utf8").includes("process.env.NODE_ENV")) {
    fail("Packed validateTheme lost the runtime process.env.NODE_ENV branch");
  }
}
