import type { NextConfig } from "next";
import path from "node:path";
import { fileURLToPath } from "node:url";

const workspaceRoot = path.join(path.dirname(fileURLToPath(import.meta.url)), "../..");

/**
 * The `apps/docs` host recipe without the MDX pipeline (ticket 77 ruling): the library is
 * consumed through its workspace source exports, so an edit under `packages/ui/src` is
 * picked up by Fast Refresh with no package build in between (architecture.md §8).
 */
const nextConfig: NextConfig = {
  outputFileTracingRoot: workspaceRoot,
  /**
   * `next dev` otherwise writes `AGENTS.md`/`CLAUDE.md` into this app on every start.
   * Agent instructions in this repo are authored, not generated by a dev server.
   */
  agentRules: false,
};

export default nextConfig;
