import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { COMPONENT_SOURCE_DIR } from "./entries";
import type { JsExportEntry } from "./entries";
import { toPosix } from "./paths";

/**
 * The per-entry Tailwind source stylesheets, `source/<entry>.css`: the `@source` lines that
 * scan exactly the published files one entry's classes can live in. They are built from the
 * published JavaScript, not the TypeScript source, because tsdown drops type-only imports and
 * the source walk in `entries.ts` reads single-line import clauses only; the published graph
 * is what a consumer's Tailwind build scans. `build-css.ts` writes them from `dist/` after
 * tsdown, and `package-check-packed.ts` recomputes them from the extracted tarball and
 * requires each packed stylesheet to match.
 */

/** One generated Tailwind source stylesheet. */
export type ComponentSourceEntry = {
  /** The entry's subpath, such as `button` or `react-aria/calendar`. */
  subpath: string;
  /** The stylesheet's path inside the published root, such as `source/button.css`. */
  distFile: string;
  /** The published JS files the entry reaches, relative to the published root, sorted. */
  publishedFiles: readonly string[];
};

/** The relative specifiers a published ESM module imports or re-exports. tsdown writes one clause per line. */
const PUBLISHED_RELATIVE_IMPORT = /(?:import|export)\s+(?:[^'"\n;]*?\sfrom\s+)?["'](\.[^"']+\.js)["']/gu;

/** The stylesheet path of one entry inside the published root. */
export function componentSourceDistFile(subpath: string): string {
  return `${COMPONENT_SOURCE_DIR}/${subpath}.css`;
}

/**
 * Every published module one entry reaches through relative imports, the entry's own module
 * included, as paths relative to the published root, sorted.
 *
 * @param publishedRoot - `dist/` after a build, or the extracted tarball.
 * @param entryFile - The entry's published module, such as `button.js`.
 * @returns The sorted closure.
 * @throws When a specifier resolves to a file the root does not hold.
 */
export function walkPublishedImports(publishedRoot: string, entryFile: string): string[] {
  const pending = [toPosix(entryFile)];
  const seen = new Set<string>();
  while (pending.length > 0) {
    const file = pending.pop();
    if (file === undefined || seen.has(file)) {
      continue;
    }
    const absolute = join(publishedRoot, file);
    if (!existsSync(absolute)) {
      throw new Error(`Published module ${file} is missing from ${publishedRoot}`);
    }
    seen.add(file);
    const text = readFileSync(absolute, "utf8");
    for (const match of text.matchAll(PUBLISHED_RELATIVE_IMPORT)) {
      const specifier = match[1];
      if (specifier !== undefined) {
        pending.push(toPosix(join(dirname(file), specifier)));
      }
    }
  }
  return [...seen].toSorted((left, right) => left.localeCompare(right));
}

/**
 * One stylesheet per JS entry other than the root barrel, from the published graph under
 * `publishedRoot`.
 */
export function componentSourceEntries(
  publishedRoot: string,
  jsEntries: readonly JsExportEntry[]
): ComponentSourceEntry[] {
  return jsEntries
    .filter((entry) => entry.subpath !== ".")
    .map((entry) => ({
      subpath: entry.subpath,
      distFile: componentSourceDistFile(entry.subpath),
      publishedFiles: walkPublishedImports(publishedRoot, `${entry.subpath}.js`),
    }));
}

/**
 * The text of one stylesheet: a banner, then one `@source` per published file. Tailwind
 * resolves `@source` relative to the stylesheet that declares it, so each path climbs out of
 * the stylesheet's own directory under `source/` first.
 */
export function renderComponentSourceCss(entry: ComponentSourceEntry): string {
  const up = "../".repeat(entry.distFile.split("/").length - 1);
  return [
    `/* Generated by scripts/build-css.ts from the published import graph of @elmeragroup/fuse/${entry.subpath}. */`,
    "/* Import this file into a Tailwind stylesheet to scan only the files that entry's classes live in. */",
    ...entry.publishedFiles.map((file) => `@source "${up}${file}";`),
    "",
  ].join("\n");
}

/** The `@source` paths one stylesheet declares, resolved against the published root, sorted. */
export function declaredSources(publishedRoot: string, distFile: string): string[] {
  const text = readFileSync(join(publishedRoot, distFile), "utf8");
  return [...text.matchAll(/^@source\s+"([^"]+)";$/gmu)]
    .map((match) => toPosix(join(dirname(distFile), match[1] ?? "")))
    .toSorted((left, right) => left.localeCompare(right));
}
