/** Exhaustive curated Phosphor roster. Adding or removing a name is a public API change. */
export const PHOSPHOR_ICON_NAMES = [
  "ArrowLeft",
  "ArrowRight",
  "ArrowsClockwise",
  "ArrowsDownUp",
  "ArrowsOut",
  "ArrowSquareOut",
  "Backspace",
  "Bell",
  "Buildings",
  "Bug",
  "Calculator",
  "CalendarBlank",
  "Camera",
  "CaretDown",
  "CaretLeft",
  "CaretRight",
  "CaretUp",
  "CaretUpDown",
  "ChartBar",
  "ChartLine",
  "ChartLineUp",
  "Check",
  "CheckCircle",
  "Circle",
  "Cloud",
  "CloudArrowUp",
  "Confetti",
  "Copy",
  "CreditCard",
  "CurrencyCircleDollar",
  "DeviceMobile",
  "Dot",
  "DotOutline",
  "DotsThree",
  "DotsThreeVertical",
  "Download",
  "Envelope",
  "Equals",
  "Eye",
  "EyeSlash",
  "FileArrowUp",
  "FileMagnifyingGlass",
  "Files",
  "Flag",
  "FloppyDisk",
  "Folder",
  "Funnel",
  "Gauge",
  "Gear",
  "Graph",
  "HandCoins",
  "Hash",
  "House",
  "IdentificationBadge",
  "Info",
  "Keyboard",
  "Lifebuoy",
  "Lightning",
  "Link",
  "List",
  "ListChecks",
  "ListNumbers",
  "Lock",
  "MagnifyingGlass",
  "MapPin",
  "Minus",
  "Money",
  "Notebook",
  "NotePencil",
  "Package",
  "Paperclip",
  "PaperPlaneTilt",
  "Pencil",
  "Percent",
  "Phone",
  "Plug",
  "Plus",
  "Prohibit",
  "Receipt",
  "Scroll",
  "SealCheck",
  "SealPercent",
  "ShareNetwork",
  "ShieldCheck",
  "ShoppingCart",
  "Sidebar",
  "SidebarSimple",
  "SignOut",
  "SpinnerGap",
  "Stack",
  "Star",
  "StopCircle",
  "Storefront",
  "Textbox",
  "Translate",
  "Trash",
  "Tray",
  "TrendDown",
  "TrendUp",
  "Truck",
  "Upload",
  "User",
  "UserCircleGear",
  "UserFocus",
  "UserPlus",
  "Users",
  "Warning",
  "WarningCircle",
  "WarningOctagon",
  "X",
  "XCircle",
] as const;

export type PhosphorIconName = (typeof PHOSPHOR_ICON_NAMES)[number];

/** Bespoke icon and logo names published from `/icons`. Extended only by the assets ticket. */
export const BESPOKE_ICON_NAMES = [
  "AlertMark",
  "BankIdDna",
  "BankIdSweden",
  "CollectLogo",
  "Contract",
  "DeviateLogo",
  "DoubleCheck",
  "FunnelLogo",
  "HomeTitleIcon",
  "OrderLogo",
  "Signing",
  "StromSmart",
  "Vipps",
] as const;

export type BespokeIconName = (typeof BESPOKE_ICON_NAMES)[number];

export const LOGO_NAMES = [
  "ElmeraGroupLogo",
  "FjordkraftLogo",
  "GudbrandsdalEnergiLogo",
  "SteddiLogo",
  "TelinetLogo",
  "TrondelagkraftLogo",
  "TrumfLogo",
] as const;

export type LogoName = (typeof LOGO_NAMES)[number];
