/**
 * The docs generation pass.
 *
 * Runs before `next build`, `next dev` and `tsc`. Component pages themselves are
 * hand-authored `page.mdx` route files compiled by `@next/mdx` (§1); this pass reads them
 * as data and writes everything they render *from*, under `src/generated` plus the static
 * markdown endpoints under `public/components`:
 *
 *   • the registry — the page's frontmatter and demos, API tables resolved from TS types
 *     + JSDoc with an RSC status, and the tokens each component's recipe reads (§3.4, §8);
 *   • each component's `api.json`, written *next to its page* and **committed**, so an API
 *     change is a reviewable diff; a drift check fails when a committed one is stale (§8);
 *   • `/components/<slug>.md` — the markdown endpoint the page links to (§9);
 *   • the ⌘K search index — the page manifest plus the registry, so the palette lists
 *     exactly the routes the site actually has (§3.2).
 *
 * Nothing is copied or compiled here: a demo is one file, imported by the page and read
 * by this pass (§6). Any unresolvable type or undocumented public prop fails this pass,
 * and therefore the docs build (§8).
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

import { normalizeDemoSource } from "../src/lib/docs-model.ts";
import type { DocsComponent, DocsDemo } from "../src/lib/docs-model.ts";
import { STATIC_PAGES } from "../src/lib/pages.ts";
import { API_REGEN_COMMAND, buildApiArtifact, serializeApiArtifact } from "./lib/api-artifact.ts";
import { describeComponentApi, openLibraryProject } from "./lib/api.ts";
import type { LibraryProject } from "./lib/api.ts";
import { componentSlugs, resolveComponentPaths } from "./lib/components.ts";
import { ProblemLog } from "./lib/errors.ts";
import { renderLlmsTxt } from "./lib/llms.ts";
import { renderComponentMarkdown } from "./lib/markdown.ts";
import { readComponentPage } from "./lib/page-source.ts";
import type { PageDemo } from "./lib/page-source.ts";
import {
  docsRouteGroup,
  generatedDir,
  llmsTxtFile,
  markdownOutDir,
  REPO_BLOB_BASE,
  repoRelative,
  sizeBudgetsFile,
  uiSrc,
} from "./lib/paths.ts";
import { renderSearchIndex } from "./lib/search.ts";
import { readBundleSizes } from "./lib/sizes.ts";
import type { BundleSizeReport } from "./lib/sizes.ts";
import { collectRecipeSources } from "./lib/sources.ts";
import { extractTokens, readColorTokenMapFromFile } from "./lib/tokens.ts";
import type { ColorTokenMap } from "./lib/tokens.ts";

const BANNER = "/* Generated by apps/docs/scripts/generate.ts. Do not edit. */\n";

const written = new Set<string>();

/**
 * Writes only when the bytes actually change, and reports whether it had to.
 *
 * `build` regenerates before bundling while turbo may already have run the `generate`
 * task for the root lint; rewriting unchanged files would briefly truncate a module
 * another task is reading. An unchanged run touches nothing.
 */
function writeFile(target: string, contents: string): boolean {
  written.add(target);
  if (existsSync(target) && readFileSync(target, "utf8") === contents) {
    return false;
  }
  mkdirSync(path.dirname(target), { recursive: true });
  writeFileSync(target, contents, "utf8");
  return true;
}

/** Removes files a previous run left behind, so a deleted demo cannot linger. */
function pruneStale(directory: string): void {
  if (!existsSync(directory)) {
    return;
  }
  for (const entry of readdirSync(directory)) {
    const target = path.join(directory, entry);
    if (statSync(target).isDirectory()) {
      pruneStale(target);
      if (readdirSync(target).length === 0) {
        rmSync(target, { recursive: true, force: true });
      }
      continue;
    }
    if (!written.has(target)) {
      rmSync(target, { force: true });
    }
  }
}

/**
 * One demo, read from the file the page imports — for the *generated* outputs only: the
 * on-page TOC entry and the source the markdown endpoint and `llms.txt` embed (§9). The
 * frame the page renders reads the same file itself (`src/lib/demo-source.ts`), so this
 * pass never produces the markup a page displays.
 *
 * The read is still here because this pass is where a page's demo *inventory* is checked:
 * a named file that does not exist, and a demo file no page renders, both fail generation.
 * The `"use client"` directive is *authored in the demo file* —
 * namespace compounds (`Dialog.Root`, `ScrollArea.Bar`) are plain objects exported from
 * client modules, and a server component only ever sees an opaque client *reference* for
 * such an export, so member access on it resolves to `undefined`. A consumer writes the
 * directive for the same reason; a demo missing it is a problem, not something this pass
 * papers over. A missing or wrongly-named export needs no check here — the page imports
 * it by name, so the bundler fails on it.
 */
function readDemo(demosDir: string, entry: PageDemo, problems: ProblemLog): DocsDemo | null {
  const absolute = path.join(demosDir, entry.file);
  const relative = repoRelative(absolute);
  if (!existsSync(absolute)) {
    problems.add(`${relative}: the page renders this demo, but the file does not exist`);
    return null;
  }
  const raw = readFileSync(absolute, "utf8");
  if (!/^\s*["']use client["']/.test(raw)) {
    problems.add(`${relative}: a demo must start with a "use client" directive`);
  }
  return {
    id: entry.id,
    title: entry.title,
    sourcePath: relative,
    source: normalizeDemoSource(raw),
  };
}

function buildComponent(
  context: LibraryProject,
  slug: string,
  problems: ProblemLog,
  colors: ColorTokenMap
): DocsComponent {
  const paths = resolveComponentPaths(slug);
  const page = readComponentPage(paths.pageFile, slug, repoRelative(paths.pageFile));

  if (!existsSync(paths.entryFile)) {
    problems.add(`${slug}: no public entry module at ${repoRelative(paths.entryFile)}`);
  }
  if (!existsSync(paths.sourceFile)) {
    problems.add(`${slug}: no implementation file at ${repoRelative(paths.sourceFile)}`);
  }
  if (!existsSync(paths.demosDir)) {
    problems.add(`${slug}: no co-located demos directory at ${repoRelative(paths.demosDir)}`);
  }

  // A demo file nobody renders is drift the build refuses to paper over: it would ship
  // as an unreachable page section and as a VR target with no documentation.
  const rendered = new Set(page.demos.map((demo) => demo.file));
  if (existsSync(paths.demosDir)) {
    for (const entry of readdirSync(paths.demosDir)) {
      if (entry.endsWith(".tsx") && !rendered.has(entry)) {
        problems.add(`${slug}: demo file ${entry} is never rendered by the page`);
      }
    }
  }

  const demos: DocsDemo[] = [];
  for (const entry of page.demos) {
    const demo = readDemo(paths.demosDir, entry, problems);
    if (demo !== null) {
      demos.push(demo);
    }
  }

  const parts = describeComponentApi(
    context,
    { entryFile: paths.entryFile, exportName: paths.exportName },
    problems
  );

  const recipe = collectRecipeSources(paths.componentDir);
  const tokens = extractTokens({ sources: recipe.sources, stylesheets: recipe.stylesheets, colors });

  const rootPart = parts.find((part) => part.sourcePath === repoRelative(paths.sourceFile)) ?? parts[0];

  return {
    slug,
    title: page.title,
    lede: page.lede,
    entry: paths.entry,
    exportName: paths.exportName,
    sourcePath: repoRelative(paths.sourceFile),
    sourceUrl: `${REPO_BLOB_BASE}/${repoRelative(paths.sourceFile)}`,
    markdownUrl: `/components/${slug}.md`,
    rsc: rootPart?.rsc ?? "client",
    headings: page.headings,
    demos,
    parts,
    tokens,
  };
}

function emitRegistry(components: readonly DocsComponent[]): void {
  writeFile(
    path.join(generatedDir, "registry.ts"),
    `${BANNER}import type { DocsComponent } from "../lib/docs-model";

export const DOCS_COMPONENTS: readonly DocsComponent[] = ${JSON.stringify(components, null, 2)};
`
  );
}

/**
 * The committed per-component `api.json`, written next to its `page.mdx` (§8).
 *
 * These files are tracked, unlike everything under `src/generated`: the point is the
 * reviewable diff. That makes staleness possible, so this also records which artifacts
 * this run had to rewrite — a rewrite means the committed file did *not* match the
 * library, and the drift check turns that into a red test naming the regen command.
 * Recording it is the only way the check survives running after this pass, which is
 * exactly what the `test` task does (it depends on `build`, which regenerates).
 */
function emitApiArtifacts(components: readonly DocsComponent[]): void {
  const stale: string[] = [];
  for (const component of components) {
    const text = serializeApiArtifact(buildApiArtifact(component.slug, component.parts));
    if (writeFile(resolveComponentPaths(component.slug).apiFile, text)) {
      stale.push(component.slug);
    }
  }
  writeFile(
    path.join(generatedDir, "api-drift.ts"),
    `${BANNER}/**
 * Slugs whose committed \`api.json\` did not match the library when the last generation
 * pass ran, and were rewritten. Non-empty means the artifacts in the working tree were
 * stale — the drift check fails on it, naming \`${API_REGEN_COMMAND}\`.
 */
export const API_ARTIFACTS_REWRITTEN: readonly string[] = ${JSON.stringify(stale, null, 2)};
`
  );
}

function emitMarkdownEndpoints(components: readonly DocsComponent[]): void {
  for (const component of components) {
    writeFile(path.join(markdownOutDir, `${component.slug}.md`), renderComponentMarkdown(component));
  }
}

/** The measured bundle sizes the Tokens page publishes (performance.md §2). */
function emitBundleSizes(report: BundleSizeReport): void {
  writeFile(
    path.join(generatedDir, "bundle-sizes.ts"),
    `${BANNER}import type { BundleSize } from "../lib/docs-model";

/** The date the library last recorded these measurements next to its budgets. */
export const BUNDLE_SIZES_MEASURED_ON = ${JSON.stringify(report.measuredOn)};

export const BUNDLE_SIZES: readonly BundleSize[] = ${JSON.stringify(report.entries, null, 2)};
`
  );
}

/** The theme tokens the Tokens page lists, read from the library's own `@theme` block. */
function emitTokenReference(colors: ColorTokenMap): void {
  const tokens = [...new Set(colors.values())].sort((left, right) => left.localeCompare(right));
  writeFile(
    path.join(generatedDir, "token-reference.ts"),
    `${BANNER}/** Every colour token a Tailwind utility in the library resolves to. */
export const COLOR_TOKENS: readonly string[] = ${JSON.stringify(tokens, null, 2)};
`
  );
}

/**
 * Every authored nav destination has to be a real route.
 *
 * The Components group is generated from the route directories that just built, so it
 * cannot point at a missing page; the Overview and Handbook groups are authored, and this
 * is what stops one of them from shipping a 404 in the SideNav (§3.3).
 */
function verifyStaticRoutes(problems: ProblemLog): void {
  for (const page of STATIC_PAGES) {
    const route = path.join(docsRouteGroup, page.href, "page.tsx");
    if (!existsSync(route)) {
      problems.add(`nav entry ${page.href} has no route at ${repoRelative(route)}`);
    }
  }
}

/** The ⌘K palette index (§3.2). */
function emitSearchIndex(components: readonly DocsComponent[]): void {
  writeFile(path.join(generatedDir, "search-index.ts"), `${BANNER}${renderSearchIndex(components)}`);
}

/** The site-root AI index (§9). */
function emitLlmsTxt(components: readonly DocsComponent[]): void {
  writeFile(llmsTxtFile, renderLlmsTxt(components));
}

function main(): void {
  const problems = new ProblemLog();
  const colors = readColorTokenMapFromFile(path.join(uiSrc, "styles/ui.css"));
  const context = openLibraryProject();
  try {
    const components = componentSlugs().map((slug) => buildComponent(context, slug, problems, colors));
    verifyStaticRoutes(problems);
    const sizes = readBundleSizes(sizeBudgetsFile, problems);
    problems.throwIfFailed();
    emitRegistry(components);
    emitApiArtifacts(components);
    emitBundleSizes(sizes);
    emitTokenReference(colors);
    emitMarkdownEndpoints(components);
    emitSearchIndex(components);
    emitLlmsTxt(components);
    pruneStale(generatedDir);
    pruneStale(markdownOutDir);
    process.stdout.write(
      `docs: generated ${String(components.length)} component pages, ${String(
        components.reduce((total, component) => total + component.demos.length, 0)
      )} demos, ${String(
        components.reduce((total, component) => total + component.parts.length, 0)
      )} API tables\n`
    );
  } finally {
    context.close();
  }
}

try {
  main();
} catch (error) {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
  // Leave no half-written registry behind for the bundler to pick up.
  rmSync(path.join(generatedDir, "registry.ts"), { force: true });
}
