/**
 * The docs generation pass.
 *
 * Runs before `next build`, `next dev` and `tsc`, and writes everything under
 * `src/generated` plus the static markdown endpoints under `public/components`:
 *
 *   • demo modules — verbatim copies of the authored `packages/ui` demo files, so the
 *     live render and the displayed source in the frame come from one file (§3.5, §6);
 *   • compiled MDX shells — the custom MDX pipeline, ahead of the bundler (§1);
 *   • the registry — API tables resolved from TS types + JSDoc with an RSC status, and
 *     the tokens each component's recipe reads (§3.4, §8);
 *   • `/components/<slug>.md` — the markdown endpoint the page links to (§9).
 *
 * Any unresolvable type or undocumented public prop fails this pass, and therefore the
 * docs build (§8).
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

import type { DocsComponent, DocsDemo } from "../src/lib/docs-model.ts";
import { STATIC_PAGES } from "../src/lib/pages.ts";
import { describeComponentApi, openLibraryProject } from "./lib/api.ts";
import type { LibraryProject } from "./lib/api.ts";
import { extractDemo } from "./lib/demos.ts";
import { ProblemLog } from "./lib/errors.ts";
import { parseShellFrontmatter, splitFrontmatter } from "./lib/frontmatter.ts";
import type { ShellFrontmatter } from "./lib/frontmatter.ts";
import { renderLlmsTxt } from "./lib/llms.ts";
import { renderComponentMarkdown } from "./lib/markdown.ts";
import { compileMdx, hasBodyContent, readContentHeadings } from "./lib/mdx.ts";
import {
  contentDir,
  docsRoot,
  docsRouteGroup,
  generatedDir,
  llmsTxtFile,
  markdownOutDir,
  REPO_BLOB_BASE,
  repoRelative,
  repoRoot,
  sizeBudgetsFile,
  uiSrc,
} from "./lib/paths.ts";
import { readBundleSizes } from "./lib/sizes.ts";
import type { BundleSizeReport } from "./lib/sizes.ts";
import { collectRecipeSources } from "./lib/sources.ts";
import { extractTokens, readColorTokenMapFromFile } from "./lib/tokens.ts";
import type { ColorTokenMap } from "./lib/tokens.ts";

const BANNER = "/* Generated by apps/docs/scripts/generate.ts. Do not edit. */\n";

function pascalCase(slug: string): string {
  return slug
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function shellFiles(): readonly string[] {
  if (!existsSync(contentDir)) {
    return [];
  }
  return readdirSync(contentDir)
    .filter((entry) => entry.endsWith(".mdx"))
    .sort((left, right) => left.localeCompare(right))
    .map((entry) => path.join(contentDir, entry));
}

type ShellPaths = {
  entryFile: string;
  entry: string;
  exportName: string;
  sourceFile: string;
  componentDir: string;
  demosDir: string;
};

function resolveShellPaths(slug: string, frontmatter: ShellFrontmatter): ShellPaths {
  const componentDir = path.join(uiSrc, "components", slug);
  const sourceFile =
    frontmatter.source === null
      ? path.join(componentDir, `${slug}.tsx`)
      : path.join(repoRoot, frontmatter.source);
  return {
    entryFile: path.join(uiSrc, `${slug}.ts`),
    entry: frontmatter.entry ?? `@elmeragroup/ui/${slug}`,
    exportName: frontmatter.exportName ?? pascalCase(slug),
    sourceFile,
    componentDir,
    demosDir: path.join(componentDir, "demos"),
  };
}

const written = new Set<string>();

/**
 * Writes only when the bytes actually change.
 *
 * `build` regenerates before bundling while turbo may already have run the `generate`
 * task for the root lint; rewriting unchanged files would briefly truncate a module
 * another task is reading. An unchanged run touches nothing.
 */
function writeFile(target: string, contents: string): void {
  written.add(target);
  if (existsSync(target) && readFileSync(target, "utf8") === contents) {
    return;
  }
  mkdirSync(path.dirname(target), { recursive: true });
  writeFileSync(target, contents, "utf8");
}

/** Removes files a previous run left behind, so a deleted demo cannot linger. */
function pruneStale(directory: string): void {
  if (!existsSync(directory)) {
    return;
  }
  for (const entry of readdirSync(directory)) {
    const target = path.join(directory, entry);
    if (statSync(target).isDirectory()) {
      pruneStale(target);
      if (readdirSync(target).length === 0) {
        rmSync(target, { recursive: true, force: true });
      }
      continue;
    }
    if (!written.has(target)) {
      rmSync(target, { force: true });
    }
  }
}

/**
 * The renderable copy of an authored demo.
 *
 * The file is copied verbatim — the frame's displayed source and its live render come
 * from the same bytes — with one addition: a `"use client"` directive. Namespace
 * compounds (`Dialog.Root`, `ScrollArea.Bar`) are plain objects exported from client
 * modules, and a server component only ever sees an opaque client *reference* for such
 * an export, so member access on it resolves to `undefined`. Pulling the demo into the
 * client graph is what a consumer would do for the same reason.
 */
function demoModule(demosDir: string, file: string): string {
  const source = readFileSync(path.join(demosDir, file), "utf8");
  return /^\s*["']use client["']/.test(source) ? source : `"use client";\n\n${source}`;
}

async function buildComponent(
  context: LibraryProject,
  file: string,
  problems: ProblemLog,
  colors: ColorTokenMap
): Promise<DocsComponent> {
  const slug = path.basename(file, ".mdx");
  const raw = readFileSync(file, "utf8");
  const split = splitFrontmatter(raw);
  const frontmatter = parseShellFrontmatter(split.frontmatter, repoRelative(file));
  const paths = resolveShellPaths(slug, frontmatter);

  if (!existsSync(paths.entryFile)) {
    problems.add(`${slug}: no public entry module at ${repoRelative(paths.entryFile)}`);
  }
  if (!existsSync(paths.sourceFile)) {
    problems.add(`${slug}: no implementation file at ${repoRelative(paths.sourceFile)}`);
  }
  if (!existsSync(paths.demosDir)) {
    problems.add(`${slug}: no co-located demos directory at ${repoRelative(paths.demosDir)}`);
  }

  // A demo file that exists but is not declared, or a declared demo that does not
  // exist, is a drift the build refuses to paper over.
  const declared = new Set(frontmatter.demos.map((demo) => demo.file));
  if (existsSync(paths.demosDir)) {
    for (const entry of readdirSync(paths.demosDir)) {
      if (entry.endsWith(".tsx") && !declared.has(entry)) {
        problems.add(`${slug}: demo file ${entry} is not listed in the page frontmatter`);
      }
    }
  }
  for (const demo of frontmatter.demos) {
    if (!existsSync(path.join(paths.demosDir, demo.file))) {
      problems.add(`${slug}: frontmatter lists a missing demo file ${demo.file}`);
    }
  }

  const demos: DocsDemo[] = [];
  for (const entry of frontmatter.demos) {
    const demo = extractDemo(context, { slug, demosDir: paths.demosDir, entry }, problems);
    if (demo !== null) {
      demos.push(demo);
      writeFile(path.join(generatedDir, "demos", slug, entry.file), demoModule(paths.demosDir, entry.file));
    }
  }

  const parts = describeComponentApi(
    context,
    { entryFile: paths.entryFile, exportName: paths.exportName },
    problems
  );

  const recipe = collectRecipeSources(paths.componentDir);
  const tokens = extractTokens({ sources: recipe.sources, stylesheets: recipe.stylesheets, colors });

  const rootPart = parts.find((part) => part.sourcePath === repoRelative(paths.sourceFile)) ?? parts[0];

  const compiled = await compileMdx(split.body, file);
  writeFile(path.join(generatedDir, "content", `${slug}.tsx`), compiled);

  return {
    slug,
    title: frontmatter.title,
    lede: frontmatter.lede,
    entry: paths.entry,
    sourcePath: repoRelative(paths.sourceFile),
    sourceUrl: `${REPO_BLOB_BASE}/${repoRelative(paths.sourceFile)}`,
    markdownUrl: `/components/${slug}.md`,
    rsc: rootPart?.rsc ?? "client",
    headings: readContentHeadings(split.body),
    demos,
    parts,
    tokens,
    hasContent: hasBodyContent(split.body),
  };
}

function emitRegistry(components: readonly DocsComponent[]): void {
  writeFile(
    path.join(generatedDir, "registry.ts"),
    `${BANNER}import type { DocsComponent } from "../lib/docs-model";

export const DOCS_COMPONENTS: readonly DocsComponent[] = ${JSON.stringify(components, null, 2)};
`
  );
}

function emitModules(components: readonly DocsComponent[]): void {
  const imports: string[] = [];
  const demoEntries: string[] = [];
  const contentEntries: string[] = [];

  for (const component of components) {
    const contentIdentifier = `${pascalCase(component.slug)}Content`;
    imports.push(`import ${contentIdentifier} from "./content/${component.slug}";`);
    contentEntries.push(`  ["${component.slug}", ${contentIdentifier}],`);
    for (const demo of component.demos) {
      imports.push(`import { ${demo.exportName} } from "${demo.modulePath}";`);
      demoEntries.push(`  ["${component.slug}/${demo.id}", ${demo.exportName}],`);
    }
  }

  writeFile(
    path.join(generatedDir, "modules.ts"),
    `${BANNER}import type { ComponentType } from "react";

import type { MdxContent } from "../lib/docs-model";

${imports.join("\n")}

/** Live demo components, keyed \`<slug>/<demoId>\`. */
export const DEMO_COMPONENTS = new Map<string, ComponentType>([
${demoEntries.join("\n")}
]);

/** Compiled MDX shell bodies, keyed by component slug. */
export const CONTENT_COMPONENTS = new Map<string, MdxContent>([
${contentEntries.join("\n")}
]);
`
  );
}

function emitMarkdownEndpoints(components: readonly DocsComponent[]): void {
  for (const component of components) {
    writeFile(path.join(markdownOutDir, `${component.slug}.md`), renderComponentMarkdown(component));
  }
}

/** The measured bundle sizes the Tokens page publishes (performance.md §2). */
function emitBundleSizes(report: BundleSizeReport): void {
  writeFile(
    path.join(generatedDir, "bundle-sizes.ts"),
    `${BANNER}import type { BundleSize } from "../lib/docs-model";

/** The date the library last recorded these measurements next to its budgets. */
export const BUNDLE_SIZES_MEASURED_ON = ${JSON.stringify(report.measuredOn)};

export const BUNDLE_SIZES: readonly BundleSize[] = ${JSON.stringify(report.entries, null, 2)};
`
  );
}

/** The theme tokens the Tokens page lists, read from the library's own `@theme` block. */
function emitTokenReference(colors: ColorTokenMap): void {
  const tokens = [...new Set(colors.values())].sort((left, right) => left.localeCompare(right));
  writeFile(
    path.join(generatedDir, "token-reference.ts"),
    `${BANNER}/** Every colour token a Tailwind utility in the library resolves to. */
export const COLOR_TOKENS: readonly string[] = ${JSON.stringify(tokens, null, 2)};
`
  );
}

/**
 * Every authored nav destination has to be a real route.
 *
 * The Components group is generated from the shells that just built, so it cannot point
 * at a missing page; the Overview and Handbook groups are authored, and this is what
 * stops one of them from shipping a 404 in the SideNav (§3.3).
 */
function verifyStaticRoutes(problems: ProblemLog): void {
  for (const page of STATIC_PAGES) {
    const route = path.join(docsRouteGroup, page.href, "page.tsx");
    if (!existsSync(route)) {
      problems.add(`nav entry ${page.href} has no route at ${repoRelative(route)}`);
    }
  }
}

/** The site-root AI index (§9). */
function emitLlmsTxt(components: readonly DocsComponent[]): void {
  writeFile(llmsTxtFile, renderLlmsTxt(components));
}

async function main(): Promise<void> {
  const problems = new ProblemLog();
  const colors = readColorTokenMapFromFile(path.join(uiSrc, "styles/ui.css"));
  const context = openLibraryProject();
  try {
    const components: DocsComponent[] = [];
    for (const file of shellFiles()) {
      components.push(await buildComponent(context, file, problems, colors));
    }
    verifyStaticRoutes(problems);
    const sizes = readBundleSizes(sizeBudgetsFile, problems);
    problems.throwIfFailed();
    emitRegistry(components);
    emitModules(components);
    emitBundleSizes(sizes);
    emitTokenReference(colors);
    emitMarkdownEndpoints(components);
    emitLlmsTxt(components);
    pruneStale(generatedDir);
    pruneStale(markdownOutDir);
    process.stdout.write(
      `docs: generated ${String(components.length)} component pages, ${String(
        components.reduce((total, component) => total + component.demos.length, 0)
      )} demos, ${String(
        components.reduce((total, component) => total + component.parts.length, 0)
      )} API tables\n`
    );
  } finally {
    context.close();
  }
}

try {
  await main();
} catch (error) {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
  // Leave no half-written registry behind for the bundler to pick up.
  rmSync(path.join(docsRoot, "src/generated/registry.ts"), { force: true });
}
