/**
 * The docs generation pass.
 *
 * Runs before `next build`, `next dev` and `tsc`. The site's component pages are
 * hand-authored `page.mdx` route files compiled by `@next/mdx`; this pass discovers
 * them by globbing the components route group, reads each page as *data* — its frontmatter,
 * its headings, the `<Demo>` elements it renders — and writes the artifacts that no page
 * owns:
 *
 *   • each component's `api.json`, written *next to its page* and **committed**, so an API
 *     change is a reviewable diff; a drift check fails when a committed one is stale;
 *   • the component-page manifest the nav, page intros and QuickNav import;
 *   • the tokens each component's recipe reads, and the site-wide token reference;
 *   • the `/api/themes` catalog of the 20 legal permutations, plus Figma DTCG files;
 *   • the measured bundle sizes the Tokens page publishes;
 *   • `/components/<slug>.md` — the markdown endpoint each page links to;
 *   • `llms.txt`, the site-root AI index;
 *   • the ⌘K search index;
 *   • and it verifies that every authored nav destination is a real route.
 *
 * Nothing is copied or compiled here: a demo is one file, imported by the page and read
 * both by the frame at render time and by this pass for the markdown it embeds. Any
 * unresolvable type or undocumented public prop fails this pass, and therefore the docs
 * build.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

import { resolveThemeCatalog } from "@elmeragroup/fuse/theme-catalog";
import type { ResolvedThemeCatalog } from "@elmeragroup/fuse/theme-catalog";
import type { ApiArtifactDiagnostic, GeneratedApiComponent } from "@elmeragroup/internal";

import type { DocsComponent, DocsDemo, ThemeCatalog } from "../src/lib/docs-model.ts";
import { API_REGEN_COMMAND, generateDocsApiArtifacts } from "./lib/api-artifact.ts";
import {
  componentInspections,
  docsApiInventory,
  inspectComponentDemos,
  inspectGlobalDocs,
  readRscStatus,
} from "./lib/docs-inspection.ts";
import type { ComponentInspection } from "./lib/docs-inspection.ts";
import { ProblemLog } from "./lib/errors.ts";
import { renderLlmsTxt } from "./lib/llms.ts";
import { renderComponentPages } from "./lib/manifest.ts";
import { renderComponentMarkdown } from "./lib/markdown.ts";
import {
  generatedDir,
  llmsTxtFile,
  markdownOutDir,
  REPO_BLOB_BASE,
  repoRelative,
  fuseSrc,
} from "./lib/paths.ts";
import { renderSearchIndex } from "./lib/search.ts";
import type { BundleSizeReport } from "./lib/sizes.ts";
import { collectRecipeSources } from "./lib/sources.ts";
import { renderFigmaThemeCatalog } from "./lib/theme-catalog-figma.ts";
import { buildThemeCatalog, renderThemeCatalog } from "./lib/theme-catalog.ts";
import { extractTokens, readColorTokenMapFromFile } from "./lib/tokens.ts";
import type { ColorTokenMap } from "./lib/tokens.ts";

const BANNER = "/* Generated by apps/docs/scripts/generate.ts. Do not edit. */\n";

const written = new Set<string>();

/**
 * Writes only when the bytes actually change, and reports whether it had to.
 *
 * `build` regenerates before bundling while turbo may already have run the `generate`
 * task for the root lint; rewriting unchanged files would briefly truncate a module
 * another task is reading. An unchanged run touches nothing.
 */
function writeFile(target: string, contents: string): boolean {
  written.add(target);
  if (existsSync(target) && readFileSync(target, "utf8") === contents) {
    return false;
  }
  mkdirSync(path.dirname(target), { recursive: true });
  writeFileSync(target, contents, "utf8");
  return true;
}

/** Removes files a previous run left behind, so a deleted demo cannot linger. */
function pruneStale(directory: string): void {
  if (!existsSync(directory)) {
    return;
  }
  for (const entry of readdirSync(directory)) {
    const target = path.join(directory, entry);
    if (statSync(target).isDirectory()) {
      pruneStale(target);
      if (readdirSync(target).length === 0) {
        rmSync(target, { recursive: true, force: true });
      }
      continue;
    }
    if (!written.has(target)) {
      rmSync(target, { force: true });
    }
  }
}

function buildComponent(
  inspection: ComponentInspection,
  demos: readonly DocsDemo[],
  api: GeneratedApiComponent,
  colors: ColorTokenMap
): DocsComponent {
  const { slug, page, paths } = inspection;
  const recipe = collectRecipeSources(paths.componentDir);
  const tokens = extractTokens({ sources: recipe.sources, stylesheets: recipe.stylesheets, colors });

  return {
    slug,
    title: paths.title,
    lede: page.lede,
    entry: paths.entry,
    sourcePath: repoRelative(paths.sourceFile),
    sourceUrl: `${REPO_BLOB_BASE}/${repoRelative(paths.sourceFile)}`,
    markdownUrl: `/components/${slug}.md`,
    // The page's status is the implementation module's own directive,
    // whether or not the artifact has a part declared there; the markdown endpoint
    // publishes it.
    rsc: readRscStatus(readFileSync(paths.sourceFile, "utf8")),
    headings: page.headings,
    demos,
    parts: api.parts,
    tokens,
  };
}

/** The component-page manifest the site imports. */
function emitComponentPages(components: readonly DocsComponent[]): void {
  writeFile(path.join(generatedDir, "component-pages.ts"), `${BANNER}${renderComponentPages(components)}`);
}

/**
 * Records which committed `api.json` files the generation pass had to rewrite.
 *
 * The artifacts are tracked, unlike everything under `src/generated`: the point is the
 * reviewable diff. That makes staleness possible, so the pass records which artifacts
 * it rewrote — a rewrite means the committed file did *not* match the library, and the
 * drift check turns that into a red test naming the regen command. Recording it is the
 * only way the check survives running after this pass: Turbo `test` depends on `build`,
 * and Turbo `build` / `type-check` depend on the `generate` task — that task is the
 * single regeneration. The package `build` script is `next build` and does not
 * regenerate.
 */
function emitApiDrift(artifacts: Iterable<GeneratedApiComponent>): void {
  const stale = [...artifacts].filter((artifact) => artifact.changed).map((artifact) => artifact.slug);
  writeFile(
    path.join(generatedDir, "api-drift.ts"),
    `${BANNER}/**
 * Slugs whose committed \`api.json\` did not match the library when the last generation
 * pass ran, and were rewritten. Non-empty means the artifacts in the working tree were
 * stale — the drift check fails on it, naming \`${API_REGEN_COMMAND}\`.
 */
export const API_ARTIFACTS_REWRITTEN: readonly string[] = ${JSON.stringify(stale, null, 2)};
`
  );
}

function emitMarkdownEndpoints(components: readonly DocsComponent[]): void {
  for (const component of components) {
    writeFile(path.join(markdownOutDir, `${component.slug}.md`), renderComponentMarkdown(component));
  }
}

/** The measured bundle sizes the Tokens page publishes. */
function emitBundleSizes(report: BundleSizeReport): void {
  writeFile(
    path.join(generatedDir, "bundle-sizes.ts"),
    `${BANNER}import type { BundleSize } from "../lib/docs-model";

/** The date the library last recorded these measurements next to its budgets. */
export const BUNDLE_SIZES_MEASURED_ON = ${JSON.stringify(report.measuredOn)};

export const BUNDLE_SIZES: readonly BundleSize[] = ${JSON.stringify(report.entries, null, 2)};
`
  );
}

/** The theme tokens the Tokens page lists, read from the library's own `@theme` block. */
function emitTokenReference(colors: ColorTokenMap): void {
  const tokens = [...new Set(colors.values())].sort((left, right) => left.localeCompare(right));
  writeFile(
    path.join(generatedDir, "token-reference.ts"),
    `${BANNER}/** Every colour token a Tailwind utility in the library resolves to. */
export const COLOR_TOKENS: readonly string[] = ${JSON.stringify(tokens, null, 2)};
`
  );
}

/** The static `GET /api/themes` catalog. */
function emitThemeCatalog(catalog: ThemeCatalog): void {
  writeFile(path.join(generatedDir, "theme-catalog.ts"), `${BANNER}${renderThemeCatalog(catalog)}`);
}

/** Per-mode DTCG documents for native Figma import, inlined in one module. */
function emitFigmaThemeCatalog(catalog: ResolvedThemeCatalog): void {
  writeFile(
    path.join(generatedDir, "theme-catalog-figma.ts"),
    `${BANNER}${renderFigmaThemeCatalog(catalog)}`
  );
}

/** The ⌘K palette index. */
function emitSearchIndex(components: readonly DocsComponent[]): void {
  writeFile(path.join(generatedDir, "search-index.ts"), `${BANNER}${renderSearchIndex(components)}`);
}

/** The site-root AI index. */
function emitLlmsTxt(components: readonly DocsComponent[]): void {
  writeFile(llmsTxtFile, renderLlmsTxt(components));
}

/**
 * Accepted extractor warnings are still worth a line per component: each names a type the
 * table shows as `any`. The package reports one warning per resolution, so the same site
 * repeats; the count here is of distinct sites.
 */
function reportDiagnostics(diagnostics: readonly ApiArtifactDiagnostic[]): void {
  const sites = new Map<string, Set<string>>();
  for (const { component, warning } of diagnostics) {
    const key = `${component}: ${warning.code}`;
    const site = `${repoRelative(warning.filePath)}:${String(warning.line)}`;
    sites.set(key, (sites.get(key) ?? new Set<string>()).add(site));
  }
  for (const [key, where] of sites) {
    process.stderr.write(`docs: ${key} at ${[...where].join(", ")}\n`);
  }
}

async function main(): Promise<void> {
  // Every input check runs before anything is written, so a failing run leaves the
  // committed api.json files and the generated site exactly as it found them. Global
  // inputs (workspace CSS exports, nav destinations, bundle sizes), demo inventory and
  // `"use client"` validation all belong to `docs-inspection`, the one owner of the docs
  // input checks.
  const problems = new ProblemLog();
  const sizes = inspectGlobalDocs(problems);
  const colors = readColorTokenMapFromFile(path.join(fuseSrc, "styles/fuse.css"));
  const inspections = componentInspections();
  const inspected = inspections.map((inspection) => ({
    inspection,
    demos: inspectComponentDemos(inspection, problems),
  }));
  problems.throwIfFailed();

  // Extraction writes the committed api.json files itself, only where the bytes change,
  // and throws a DocsGenerationError on any extraction problem.
  const generated = await generateDocsApiArtifacts("write", docsApiInventory(inspections));
  reportDiagnostics(generated.diagnostics);
  const components = inspected.map(({ inspection, demos }) => {
    const api = generated.artifacts.get(inspection.slug);
    if (api === undefined) {
      throw new Error(`no generated API artifact for component "${inspection.slug}"`);
    }
    return buildComponent(inspection, demos, api, colors);
  });

  emitComponentPages(components);
  emitApiDrift(generated.artifacts.values());
  emitBundleSizes(sizes);
  emitTokenReference(colors);
  const catalog = resolveThemeCatalog();
  emitThemeCatalog(buildThemeCatalog(catalog));
  emitFigmaThemeCatalog(catalog);
  emitMarkdownEndpoints(components);
  emitSearchIndex(components);
  emitLlmsTxt(components);
  pruneStale(generatedDir);
  pruneStale(markdownOutDir);
  process.stdout.write(
    `docs: generated ${String(components.length)} component pages, ${String(
      components.reduce((total, component) => total + component.demos.length, 0)
    )} demos, ${String(
      components.reduce((total, component) => total + component.parts.length, 0)
    )} API tables\n`
  );
}

try {
  await main();
} catch (error) {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
  // Leave no half-written manifest behind for the bundler to pick up.
  rmSync(path.join(generatedDir, "component-pages.ts"), { force: true });
}
