import { composeTheme } from "./compose-theme";
import { brandPointer } from "./tokens/brand-pointers";
import { EXTERNAL_RESET_KEYS, TOKEN_NAMES } from "./tokens/contract";
import type { TokenContract } from "./tokens/contract";
import { DEFAULTS } from "./tokens/defaults";
import { externalPalette } from "./tokens/external-palettes";
import { PRIMITIVE_NAMES, PRIMITIVES } from "./tokens/primitives";
import { FKAS_COMPANY_DELTA } from "./tokens/segment-deltas";
import { BRAND_CODES, LEGAL_THEMES } from "./tokens/themes";

const GENERATED_FILE_HEADER = `/**
 * AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY.
 *
 * Generated by the token pipeline. TypeScript theme modules are the source of truth.
 */

`;

const DARK_PLACEHOLDER = `/* Reserved color-scheme axis. Values land with the dark-mode roadmap item.
   Do not add an empty rule node here.
   [data-theme="dark"] {
   }
 */
`;

function cssCustomProperty(name: string, value: string): string {
  return `  --${name}: ${value};`;
}

function cssRule(selector: string, declarations: readonly (readonly [string, string])[]): string {
  const body = declarations.map(([name, value]) => cssCustomProperty(name, value)).join("\n");
  return `${selector} {\n${body}\n}`;
}

function rootDeclarations(): (readonly [string, string])[] {
  const primitives = PRIMITIVE_NAMES.map((name) => [name, PRIMITIVES[name]] as const);
  const roles = TOKEN_NAMES.map((name) => [name, DEFAULTS[name]] as const);
  return [...primitives, ...roles];
}

function resetDeclarations(overrides: Partial<TokenContract>): (readonly [string, string])[] {
  return EXTERNAL_RESET_KEYS.map((key) => {
    const value = overrides[key] ?? DEFAULTS[key];
    return [key, value] as const;
  });
}

function emitRoot(): string {
  return cssRule(":root", rootDeclarations());
}

function emitBrandPointers(): string {
  return BRAND_CODES.map((code) => {
    const pointer = brandPointer(code);
    return cssRule(`[data-theme-brand="${code}"]`, [
      ["brand", pointer.brand],
      ["brand-foreground", pointer["brand-foreground"]],
      ["sidebar-brand", DEFAULTS["sidebar-brand"]],
      ["sidebar-brand-foreground", DEFAULTS["sidebar-brand-foreground"]],
    ]);
  }).join("\n\n");
}

function emitInternalReset(): string {
  return cssRule(`[data-theme-variant="internal"]`, resetDeclarations({}));
}

function emitExternalPalettes(): string {
  return BRAND_CODES.map((code) => {
    const selector = `[data-theme-variant="external"][data-theme-brand="${code}"]`;
    return cssRule(selector, resetDeclarations(externalPalette(code)));
  }).join("\n\n");
}

function emitSegmentDelta(): string {
  return cssRule(
    `[data-theme-variant="external"][data-theme-brand="fkas"][data-theme-segment="company"]`,
    Object.entries(FKAS_COMPANY_DELTA)
  );
}

export function generateThemesCss(): string {
  for (const theme of LEGAL_THEMES) {
    composeTheme(theme);
  }

  return [
    GENERATED_FILE_HEADER.trimEnd(),
    emitRoot(),
    emitBrandPointers(),
    emitInternalReset(),
    emitExternalPalettes(),
    emitSegmentDelta(),
    DARK_PLACEHOLDER.trimEnd(),
    "",
  ].join("\n\n");
}
