import type { ReactElement } from "react";

import { tv } from "tailwind-variants";

import {
  ArrowLeft,
  ArrowRight,
  ArrowsClockwise,
  ArrowsDownUp,
  ArrowsLeftRight,
  ArrowsOut,
  ArrowSquareOut,
  Backspace,
  Bell,
  Buildings,
  Bug,
  Calculator,
  CalendarBlank,
  Camera,
  CaretDoubleLeft,
  CaretDoubleRight,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  CaretUpDown,
  ChartBar,
  ChartLine,
  ChartLineUp,
  ChatCircle,
  ChatText,
  Check,
  CheckCircle,
  Checks,
  Circle,
  ClockCounterClockwise,
  Cloud,
  CloudArrowUp,
  Confetti,
  Copy,
  CreditCard,
  CurrencyCircleDollar,
  DeviceMobile,
  Dot,
  DotOutline,
  DotsSixVertical,
  DotsThree,
  DotsThreeVertical,
  Download,
  Envelope,
  Equals,
  Eye,
  EyeSlash,
  FileArrowUp,
  FileMagnifyingGlass,
  Files,
  Flag,
  FlagPennant,
  Flask,
  FloppyDisk,
  Folder,
  Funnel,
  FunnelSimple,
  Gauge,
  Gear,
  Graph,
  HandCoins,
  Hash,
  House,
  IdentificationBadge,
  Info,
  Keyboard,
  Lifebuoy,
  Lightning,
  Link,
  List,
  ListChecks,
  ListMagnifyingGlass,
  ListNumbers,
  Lock,
  MagnifyingGlass,
  MapPin,
  Minus,
  Money,
  Notebook,
  NotePencil,
  Package,
  Paperclip,
  PaperPlaneTilt,
  Pencil,
  Percent,
  Phone,
  Plug,
  PlugCharging,
  Plus,
  Prohibit,
  PuzzlePiece,
  Receipt,
  Scroll,
  SealCheck,
  SealPercent,
  ShareNetwork,
  ShieldCheck,
  ShoppingCart,
  Sidebar,
  SidebarSimple,
  SignOut,
  SlidersHorizontal,
  SpinnerGap,
  SquaresFour,
  Stack,
  Star,
  StopCircle,
  Storefront,
  Textbox,
  Translate,
  Trash,
  Tray,
  TrendDown,
  TrendUp,
  Truck,
  Upload,
  User,
  UserCircleGear,
  UserFocus,
  UserPlus,
  Users,
  Warning,
  WarningCircle,
  WarningOctagon,
  X,
  XCircle,
} from "@elmeragroup/fuse/icons";
import type { ElmeraIconProps } from "@elmeragroup/fuse/icons";

/** The curated Phosphor roster, in the order `@elmeragroup/fuse/icons` publishes it. */
const ROSTER = Object.entries({
  ArrowLeft,
  ArrowRight,
  ArrowsClockwise,
  ArrowsDownUp,
  ArrowsLeftRight,
  ArrowsOut,
  ArrowSquareOut,
  Backspace,
  Bell,
  Buildings,
  Bug,
  Calculator,
  CalendarBlank,
  Camera,
  CaretDoubleLeft,
  CaretDoubleRight,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  CaretUpDown,
  ChartBar,
  ChartLine,
  ChartLineUp,
  ChatCircle,
  ChatText,
  Check,
  CheckCircle,
  Checks,
  Circle,
  ClockCounterClockwise,
  Cloud,
  CloudArrowUp,
  Confetti,
  Copy,
  CreditCard,
  CurrencyCircleDollar,
  DeviceMobile,
  Dot,
  DotOutline,
  DotsSixVertical,
  DotsThree,
  DotsThreeVertical,
  Download,
  Envelope,
  Equals,
  Eye,
  EyeSlash,
  FileArrowUp,
  FileMagnifyingGlass,
  Files,
  Flag,
  FlagPennant,
  Flask,
  FloppyDisk,
  Folder,
  Funnel,
  FunnelSimple,
  Gauge,
  Gear,
  Graph,
  HandCoins,
  Hash,
  House,
  IdentificationBadge,
  Info,
  Keyboard,
  Lifebuoy,
  Lightning,
  Link,
  List,
  ListChecks,
  ListMagnifyingGlass,
  ListNumbers,
  Lock,
  MagnifyingGlass,
  MapPin,
  Minus,
  Money,
  Notebook,
  NotePencil,
  Package,
  Paperclip,
  PaperPlaneTilt,
  Pencil,
  Percent,
  Phone,
  Plug,
  PlugCharging,
  Plus,
  Prohibit,
  PuzzlePiece,
  Receipt,
  Scroll,
  SealCheck,
  SealPercent,
  ShareNetwork,
  ShieldCheck,
  ShoppingCart,
  Sidebar,
  SidebarSimple,
  SignOut,
  SlidersHorizontal,
  SpinnerGap,
  SquaresFour,
  Stack,
  Star,
  StopCircle,
  Storefront,
  Textbox,
  Translate,
  Trash,
  Tray,
  TrendDown,
  TrendUp,
  Truck,
  Upload,
  User,
  UserCircleGear,
  UserFocus,
  UserPlus,
  Users,
  Warning,
  WarningCircle,
  WarningOctagon,
  X,
  XCircle,
} satisfies Record<string, (props: ElmeraIconProps) => ReactElement>);

/** The three sizes products draw icons at most: 12px, 16px and 20px. */
const SIZES = ["size-3", "size-4", "size-5"] as const;

const iconRoster = tv({
  slots: {
    root: "not-prose flex w-full flex-col gap-6",
    label: "text-xs font-mono text-muted-foreground",
    grid: "flex flex-wrap gap-3 text-foreground",
  },
});

const { root, label, grid } = iconRoster();

/**
 * Every curated icon at the default weight, once per size, so stroke weight can be
 * reviewed by eye. Hover an icon to read its name.
 */
export function IconRoster(): ReactElement {
  return (
    <div className={root()}>
      {SIZES.map((size) => (
        <section key={size} aria-label={size}>
          <p className={label()}>{size}</p>
          <div className={grid()}>
            {ROSTER.map(([name, Icon]) => (
              <Icon key={name} title={name} className={size} />
            ))}
          </div>
        </section>
      ))}
    </div>
  );
}
