/**
 * One specimen per component page, keyed by the generated slug union, so a new page without a
 * specimen fails to compile.
 */

import type { ComponentSlug } from "../generated/component-pages";
import {
  breadcrumb,
  buttonGroup,
  confirmButton,
  fileTrigger,
  focusable,
  link,
  loader,
  pagination,
  popoverInfoButton,
  toggle,
  toggleGroup,
} from "./specimens/actions";
import { badge, button, input, select, switchSpecimen } from "./specimens/controls";
import {
  calendar,
  dataTable,
  dateField,
  datePicker,
  dateRangePicker,
  descriptionList,
  gridList,
  item,
  rangeCalendar,
  table,
  timelineList,
} from "./specimens/dates-data";
import {
  checkbox,
  checkboxCard,
  combobox,
  field,
  form,
  inputGroup,
  meter,
  numberField,
  phoneNumberField,
  radioGroup,
  searchField,
  selectionItem,
  textField,
  textarea,
  textareaField,
} from "./specimens/forms";
import {
  avatar,
  card,
  code,
  emoji,
  empty,
  frame,
  heading,
  scrollArea,
  separator,
  show,
  sidebar,
  skeleton,
  span,
  text,
  uiProviders,
} from "./specimens/layout-text";
import {
  accordion,
  alert,
  alertDialog,
  collapsible,
  dialog,
  dropdownMenu,
  navigationMenu,
  popover,
  sheet,
  tabs,
  toast,
  tooltip,
} from "./specimens/overlays";
import type { Specimen } from "./specimens/specimen";

/** Every component's specimen. */
export const SPECIMENS = {
  accordion,
  alert,
  "alert-dialog": alertDialog,
  avatar,
  badge,
  breadcrumb,
  button,
  "button-group": buttonGroup,
  calendar,
  card,
  checkbox,
  "checkbox-card": checkboxCard,
  code,
  collapsible,
  combobox,
  "confirm-button": confirmButton,
  "data-table": dataTable,
  "date-field": dateField,
  "date-picker": datePicker,
  "date-range-picker": dateRangePicker,
  "description-list": descriptionList,
  dialog,
  "dropdown-menu": dropdownMenu,
  emoji,
  empty,
  field,
  "file-trigger": fileTrigger,
  focusable,
  form,
  frame,
  "grid-list": gridList,
  heading,
  input,
  "input-group": inputGroup,
  item,
  link,
  loader,
  meter,
  "navigation-menu": navigationMenu,
  "number-field": numberField,
  pagination,
  "phone-number-field": phoneNumberField,
  popover,
  "popover-info-button": popoverInfoButton,
  "radio-group": radioGroup,
  "range-calendar": rangeCalendar,
  "scroll-area": scrollArea,
  "search-field": searchField,
  select,
  "selection-item": selectionItem,
  separator,
  sheet,
  show,
  sidebar,
  skeleton,
  span,
  switch: switchSpecimen,
  table,
  tabs,
  text,
  "text-field": textField,
  textarea,
  "textarea-field": textareaField,
  "timeline-list": timelineList,
  toast,
  toggle,
  "toggle-group": toggleGroup,
  tooltip,
  "ui-providers": uiProviders,
} as const satisfies Record<ComponentSlug, Specimen>;

/**
 * True when `slug` names a component page, narrowing it to the slug union.
 *
 * @param slug - A route segment.
 * @returns Whether a specimen exists for it.
 */
export function isComponentSlug(slug: string): slug is ComponentSlug {
  return Object.hasOwn(SPECIMENS, slug);
}
