import type { TokenName } from "./tokens";

/** One token of a base theme in one scheme. */
export type StudioSeedToken = {
  /** The value its theme rule declares: a literal, a `var()` alias or a `color-mix()`. */
  readonly css: string;
  /** The value at the end of its chain, as the inspector prints it, such as `#F5AA81` or `12px`. */
  readonly value: string;
};

/** Every token of a base theme in one scheme. */
export type StudioSchemeSeed = { readonly [Name in TokenName]: StudioSeedToken };

/** A base theme's tokens in both schemes, generated by `src/studio/generate/seeds.ts`. */
export type StudioSeed = {
  readonly slug: string;
  readonly light: StudioSchemeSeed;
  readonly dark: StudioSchemeSeed;
};

/** A primitive the color knob offers as a swatch. */
export type StudioPrimitive = {
  /** The custom property without its leading dashes, such as `neutral-500`. */
  readonly name: string;
  /** Its color as `#RRGGBB`. */
  readonly value: string;
};
