/**
 * Server-visible namespace for `Sidebar`.
 * The implementation stays a client module; this file has no directive,
 * so a server component can read each part instead of dotting into a client reference.
 */
import {
  Provider,
  Root,
  Trigger,
  Rail,
  Inset,
  Input,
  Header,
  Footer,
  Separator,
  Content,
  Group,
  GroupLabel,
  GroupAction,
  GroupContent,
  Menu,
  MenuItem,
  MenuButton,
  MenuAction,
  MenuBadge,
  MenuSkeleton,
  MenuSub,
  MenuSubItem,
  MenuSubButton,
  Icon,
} from "./index.parts";

export const Sidebar = {
  Provider,
  Root,
  Trigger,
  Rail,
  Inset,
  Input,
  Header,
  Footer,
  Separator,
  Content,
  Group,
  GroupLabel,
  GroupAction,
  GroupContent,
  Menu,
  MenuItem,
  MenuButton,
  MenuAction,
  MenuBadge,
  MenuSkeleton,
  MenuSub,
  MenuSubItem,
  MenuSubButton,
  Icon,
};

export {
  SIDEBAR_COOKIE_MAX_AGE,
  SIDEBAR_COOKIE_NAME,
  SIDEBAR_KEYBOARD_SHORTCUT,
  SIDEBAR_WIDTH,
  SIDEBAR_WIDTH_ICON,
  SIDEBAR_WIDTH_MOBILE,
  useSidebar,
} from "./sidebar";
export type {
  SidebarContentProps,
  SidebarContextValue,
  SidebarFooterProps,
  SidebarGroupActionProps,
  SidebarGroupContentProps,
  SidebarGroupLabelProps,
  SidebarGroupProps,
  SidebarHeaderProps,
  SidebarIconProps,
  SidebarInputProps,
  SidebarInsetProps,
  SidebarLabels,
  SidebarMenuActionProps,
  SidebarMenuBadgeProps,
  SidebarMenuButtonProps,
  SidebarMenuItemProps,
  SidebarMenuProps,
  SidebarMenuSkeletonProps,
  SidebarMenuSubButtonProps,
  SidebarMenuSubItemProps,
  SidebarMenuSubProps,
  SidebarProviderProps,
  SidebarRailProps,
  SidebarRootProps,
  SidebarSeparatorProps,
  SidebarTriggerProps,
} from "./sidebar";
